import { IndustryLandingData } from '../types';

export const petServices: IndustryLandingData = {
  slug: 'pet-services',
  name: 'Pet Services',
  icon: '🐕',
  title: 'Crypto Payments for Pet Services | 0.5-1% Fee | PortalPay',
  metaDescription: 'Pet grooming, boarding & daycare crypto payments. Pay only 0.5-1% vs 2.9%. Free booking system included. Accept cards without a bank account.',
  keywords: ['pet grooming payments', 'dog boarding crypto', 'pet daycare payments', 'pet services pos'],
  heroHeadline: 'Accept Crypto Payments for Pet Services',
  heroSubheadline: 'Groomers, boarders, and pet daycares save 70% on fees. Free booking and client management included.',
  heroCTA: { primary: 'Start Free', primaryLink: '/admin', secondary: 'Try Demo', secondaryLink: '/terminal' },
  painPoints: ['High processing fees eating into margins', 'No-shows costing revenue', 'Complex booking management', 'Expensive POS systems'],
  solutions: ['0.5-1% fees vs 2.9%', 'Prepaid booking deposits', 'Free scheduling system', 'Instant settlement'],
  benefits: [
    { icon: '💰', title: 'Save 70% on Fees', description: 'Pay 0.5-1% instead of 2.9%+', stat: '70% Savings' },
    { icon: '📅', title: 'Free Booking System', description: 'Online scheduling with deposits', stat: 'Included' },
    { icon: '⚡', title: 'Instant Payouts', description: 'Get paid immediately', stat: 'Same Day' },
  ],
  avgMonthlyVolume: 8000,
  competitorComparison: { square: { processingFee: 0.026, flatFee: 0.10, monthlyFee: 60, annualSoftwareCost: 720 } },
  useCases: [{ title: 'Grooming Appointments', description: 'Accept deposits and final payments via QR code', example: '$8k/month saves $1,920/year', savings: '$1,920/year' }],
  industryFeatures: ['Online Booking', 'Client Profiles', 'Pet Records', 'Appointment Reminders', 'Package Deals'],
  includedFeatures: [{ name: 'Booking System', description: 'Full scheduling with deposits', usualCost: '$50/mo' }],
  setupSteps: ['Connect wallet', 'Set up services', 'Enable booking', 'Start accepting payments'],
  faqs: [{ question: 'Can clients book and pay online?', answer: 'Yes, full online booking with deposit collection via crypto or card.' }],
  relatedIndustries: ['veterinarians', 'retail', 'salons'],
  relatedUseCases: ['booking-deposits', 'low-fee-processing'],
};

export const daycareChildcare: IndustryLandingData = {
  slug: 'daycare-childcare',
  name: 'Daycare & Childcare',
  icon: '👶',
  title: 'Crypto Payments for Daycare | 0.5-1% Fee | PortalPay',
  metaDescription: 'Daycare and childcare center payment processing. Pay only 0.5-1%. Free parent billing portal. Accept tuition payments easily.',
  keywords: ['daycare payments', 'childcare billing', 'tuition payments crypto'],
  heroHeadline: 'Accept Crypto Payments for Childcare',
  heroSubheadline: 'Daycare centers save thousands on tuition processing. Free parent portal included.',
  heroCTA: { primary: 'Start Free', primaryLink: '/admin', secondary: 'Try Demo', secondaryLink: '/terminal' },
  painPoints: ['High fees on recurring tuition', 'Late payment tracking', 'Parent billing complexity'],
  solutions: ['0.5-1% on all payments', 'Automated billing reminders', 'Parent payment portal'],
  benefits: [
    { icon: '💰', title: 'Save on Tuition Fees', description: 'Process $20k/month, save $4,800/year', stat: '$4,800/yr' },
    { icon: '👨‍👩‍👧', title: 'Parent Portal', description: 'Easy payment for families', stat: 'Free' },
  ],
  avgMonthlyVolume: 20000,
  competitorComparison: { stripe: { processingFee: 0.029, flatFee: 0.30, monthlyFee: 0, annualSoftwareCost: 0 } },
  useCases: [{ title: 'Monthly Tuition', description: 'Parents pay via QR code or link', example: '$20k/month saves $4,800/year', savings: '$4,800/year' }],
  industryFeatures: ['Parent Portal', 'Recurring Billing', 'Attendance Tracking', 'Payment History'],
  includedFeatures: [{ name: 'Billing Portal', description: 'Parent-facing payment interface', usualCost: '$75/mo' }],
  setupSteps: ['Connect wallet', 'Set tuition rates', 'Invite parents', 'Collect payments'],
  faqs: [{ question: 'Can parents pay with credit cards?', answer: 'Yes, our onramp converts cards to crypto automatically.' }],
  relatedIndustries: ['tutoring-education', 'gyms', 'dance-studios'],
  relatedUseCases: ['recurring-payments', 'low-fee-processing'],
};

export const tutoringEducation: IndustryLandingData = {
  slug: 'tutoring-education',
  name: 'Tutoring & Education',
  icon: '📚',
  title: 'Crypto Payments for Tutors | 0.5-1% Fee | PortalPay',
  metaDescription: 'Tutoring and education center payments. Pay only 0.5-1%. Free scheduling and session tracking included.',
  keywords: ['tutoring payments', 'education payments crypto', 'tutor pos system'],
  heroHeadline: 'Accept Crypto Payments for Tutoring',
  heroSubheadline: 'Tutors and learning centers save 70% on payment processing fees.',
  heroCTA: { primary: 'Start Free', primaryLink: '/admin', secondary: 'Try Demo', secondaryLink: '/terminal' },
  painPoints: ['Platform fees eating profits', 'Complex session billing', 'Delayed payments'],
  solutions: ['Keep more per session', 'Simple invoicing', 'Instant settlement'],
  benefits: [
    { icon: '💰', title: 'Keep More Earnings', description: 'Pay 0.5-1% vs platform 15-20%', stat: '90%+ Kept' },
    { icon: '📅', title: 'Session Scheduling', description: 'Book and bill in one place', stat: 'Included' },
  ],
  avgMonthlyVolume: 5000,
  competitorComparison: { stripe: { processingFee: 0.029, flatFee: 0.30, monthlyFee: 0, annualSoftwareCost: 0 } },
  useCases: [{ title: 'Session Payments', description: 'Students pay per session via link', example: '$5k/month saves $1,200/year', savings: '$1,200/year' }],
  industryFeatures: ['Session Scheduling', 'Student Profiles', 'Progress Tracking', 'Package Billing'],
  includedFeatures: [{ name: 'Scheduling', description: 'Session booking system', usualCost: '$30/mo' }],
  setupSteps: ['Connect wallet', 'Set hourly rates', 'Share booking link', 'Get paid'],
  faqs: [{ question: 'Can I sell lesson packages?', answer: 'Yes, create multi-session packages with discounts.' }],
  relatedIndustries: ['music-lessons', 'dance-studios', 'martial-arts'],
  relatedUseCases: ['session-payments', 'low-fee-processing'],
};

export const photographyStudios: IndustryLandingData = {
  slug: 'photography-studios',
  name: 'Photography Studios',
  icon: '📸',
  title: 'Crypto Payments for Photographers | 0.5-1% Fee | PortalPay',
  metaDescription: 'Photography studio payment processing. Pay only 0.5-1%. Accept deposits and final payments. Free invoicing included.',
  keywords: ['photography payments', 'photographer invoicing', 'studio payments crypto'],
  heroHeadline: 'Accept Crypto Payments for Photography',
  heroSubheadline: 'Photographers save 70% on processing. Accept deposits and balance payments easily.',
  heroCTA: { primary: 'Start Free', primaryLink: '/admin', secondary: 'Try Demo', secondaryLink: '/terminal' },
  painPoints: ['High fees on large invoices', 'Deposit management hassle', 'Chasing final payments'],
  solutions: ['0.5-1% on all invoices', 'Easy deposit collection', 'Professional invoicing'],
  benefits: [
    { icon: '💰', title: 'Save on Big Invoices', description: '$2,000 wedding saves $48 vs Stripe', stat: '$48/invoice' },
    { icon: '📄', title: 'Pro Invoicing', description: 'Deposits + balance billing', stat: 'Included' },
  ],
  avgMonthlyVolume: 10000,
  competitorComparison: { stripe: { processingFee: 0.029, flatFee: 0.30, monthlyFee: 0, annualSoftwareCost: 0 } },
  useCases: [{ title: 'Wedding Photography', description: 'Collect 50% deposit, balance on delivery', example: '$10k/month saves $2,400/year', savings: '$2,400/year' }],
  industryFeatures: ['Invoicing', 'Deposit Management', 'Client Galleries', 'Contract Integration'],
  includedFeatures: [{ name: 'Invoice Builder', description: 'Professional invoices with deposits', usualCost: '$40/mo' }],
  setupSteps: ['Connect wallet', 'Create service packages', 'Send invoice', 'Collect payment'],
  faqs: [{ question: 'Can I split invoices into deposit and balance?', answer: 'Yes, create multi-payment invoices easily.' }],
  relatedIndustries: ['event-planning', 'freelancers', 'art-galleries'],
  relatedUseCases: ['invoicing', 'deposit-payments'],
};

export const eventPlanning: IndustryLandingData = {
  slug: 'event-planning',
  name: 'Event Planning',
  icon: '🎉',
  title: 'Crypto Payments for Event Planners | 0.5-1% Fee | PortalPay',
  metaDescription: 'Event planning payment processing. Pay only 0.5-1%. Manage deposits, vendor payments, and client billing.',
  keywords: ['event planner payments', 'wedding planner crypto', 'event billing'],
  heroHeadline: 'Accept Crypto Payments for Event Planning',
  heroSubheadline: 'Event planners save thousands on high-value bookings. Manage all payments in one place.',
  heroCTA: { primary: 'Start Free', primaryLink: '/admin', secondary: 'Try Demo', secondaryLink: '/terminal' },
  painPoints: ['High fees on large deposits', 'Complex milestone billing', 'Vendor payment management'],
  solutions: ['0.5-1% on all transactions', 'Milestone invoicing', 'Organized payment tracking'],
  benefits: [
    { icon: '💰', title: 'Save on Big Events', description: '$10k event saves $240 vs traditional', stat: '$240/event' },
    { icon: '📊', title: 'Payment Dashboard', description: 'Track all event payments', stat: 'Included' },
  ],
  avgMonthlyVolume: 25000,
  competitorComparison: { stripe: { processingFee: 0.029, flatFee: 0.30, monthlyFee: 0, annualSoftwareCost: 0 } },
  useCases: [{ title: 'Wedding Planning', description: 'Collect deposits and milestone payments', example: '$25k/month saves $6,000/year', savings: '$6,000/year' }],
  industryFeatures: ['Milestone Billing', 'Client Portal', 'Payment Tracking', 'Multi-Event Management'],
  includedFeatures: [{ name: 'Event Dashboard', description: 'Manage multiple events', usualCost: '$100/mo' }],
  setupSteps: ['Connect wallet', 'Create event packages', 'Set milestones', 'Collect payments'],
  faqs: [{ question: 'Can I bill in milestones?', answer: 'Yes, create custom payment schedules for each event.' }],
  relatedIndustries: ['photography-studios', 'catering-services', 'florists'],
  relatedUseCases: ['milestone-billing', 'high-value-transactions'],
};

export const cateringServices: IndustryLandingData = {
  slug: 'catering-services',
  name: 'Catering Services',
  icon: '🍱',
  title: 'Crypto Payments for Caterers | 0.5-1% Fee | PortalPay',
  metaDescription: 'Catering business payment processing. Pay only 0.5-1%. Accept deposits and event payments easily.',
  keywords: ['catering payments', 'caterer invoicing', 'event catering crypto'],
  heroHeadline: 'Accept Crypto Payments for Catering',
  heroSubheadline: 'Caterers save 70% on processing fees. Handle large event payments with ease.',
  heroCTA: { primary: 'Start Free', primaryLink: '/admin', secondary: 'Try Demo', secondaryLink: '/terminal' },
  painPoints: ['High fees on large orders', 'Deposit tracking', 'Last-minute changes billing'],
  solutions: ['0.5-1% on all orders', 'Easy deposit system', 'Flexible invoicing'],
  benefits: [
    { icon: '💰', title: 'Save on Large Orders', description: '$5k catering order saves $120', stat: '$120/order' },
    { icon: '📋', title: 'Quote System', description: 'Create and convert quotes', stat: 'Included' },
  ],
  avgMonthlyVolume: 20000,
  competitorComparison: { square: { processingFee: 0.026, flatFee: 0.10, monthlyFee: 0, annualSoftwareCost: 0 } },
  useCases: [{ title: 'Corporate Catering', description: 'Invoice businesses for events', example: '$20k/month saves $4,800/year', savings: '$4,800/year' }],
  industryFeatures: ['Quote Builder', 'Menu Templates', 'Deposit Tracking', 'Event Calendar'],
  includedFeatures: [{ name: 'Quote System', description: 'Create quotes, convert to invoices', usualCost: '$50/mo' }],
  setupSteps: ['Connect wallet', 'Build menu', 'Create quote', 'Convert to invoice'],
  faqs: [{ question: 'Can I create quotes before invoicing?', answer: 'Yes, create quotes and convert to invoices when approved.' }],
  relatedIndustries: ['restaurants', 'event-planning', 'food-trucks'],
  relatedUseCases: ['invoicing', 'high-value-transactions'],
};

export const florists: IndustryLandingData = {
  slug: 'florists',
  name: 'Florists',
  icon: '💐',
  title: 'Crypto Payments for Florists | 0.5-1% Fee | PortalPay',
  metaDescription: 'Flower shop payment processing. Pay only 0.5-1%. Free online ordering and delivery management.',
  keywords: ['florist payments', 'flower shop pos', 'florist crypto'],
  heroHeadline: 'Accept Crypto Payments for Your Flower Shop',
  heroSubheadline: 'Florists save 70% on fees. Online ordering and delivery tracking included.',
  heroCTA: { primary: 'Start Free', primaryLink: '/admin', secondary: 'Try Demo', secondaryLink: '/terminal' },
  painPoints: ['High fees on small purchases', 'Wire service commissions', 'Delivery coordination'],
  solutions: ['0.5-1% flat rate', 'Direct customer orders', 'Built-in delivery tracking'],
  benefits: [
    { icon: '💰', title: 'Skip Wire Services', description: 'Avoid 20%+ wire service fees', stat: '20% Saved' },
    { icon: '🚚', title: 'Delivery System', description: 'Track and manage deliveries', stat: 'Included' },
  ],
  avgMonthlyVolume: 12000,
  competitorComparison: { square: { processingFee: 0.026, flatFee: 0.10, monthlyFee: 60, annualSoftwareCost: 720 } },
  useCases: [{ title: 'Wedding Florals', description: 'Large orders with deposits', example: '$12k/month saves $2,880/year', savings: '$2,880/year' }],
  industryFeatures: ['Online Catalog', 'Delivery Scheduling', 'Occasion Reminders', 'Event Packages'],
  includedFeatures: [{ name: 'Online Ordering', description: 'Customer-facing catalog', usualCost: '$75/mo' }],
  setupSteps: ['Connect wallet', 'Add arrangements', 'Set delivery zones', 'Accept orders'],
  faqs: [{ question: 'Can customers order online?', answer: 'Yes, full e-commerce catalog with delivery scheduling.' }],
  relatedIndustries: ['event-planning', 'retail', 'bakeries'],
  relatedUseCases: ['online-ordering', 'delivery-payments'],
};

export const printShops: IndustryLandingData = {
  slug: 'print-shops',
  name: 'Print Shops',
  icon: '🖨️',
  title: 'Crypto Payments for Print Shops | 0.5-1% Fee | PortalPay',
  metaDescription: 'Print shop payment processing. Pay only 0.5-1%. Accept orders and proofs payments easily.',
  keywords: ['print shop payments', 'printing business pos', 'copy shop crypto'],
  heroHeadline: 'Accept Crypto Payments for Printing',
  heroSubheadline: 'Print shops save 70% on processing. Handle quotes and large orders easily.',
  heroCTA: { primary: 'Start Free', primaryLink: '/admin', secondary: 'Try Demo', secondaryLink: '/terminal' },
  painPoints: ['Small margin on print jobs', 'Complex quoting', 'Rush order premiums'],
  solutions: ['Keep more per job', 'Easy quote system', 'Flexible pricing'],
  benefits: [
    { icon: '💰', title: 'Better Margins', description: 'Save 70% on every transaction', stat: '70% Savings' },
    { icon: '📝', title: 'Quote System', description: 'Quote jobs professionally', stat: 'Included' },
  ],
  avgMonthlyVolume: 8000,
  competitorComparison: { square: { processingFee: 0.026, flatFee: 0.10, monthlyFee: 0, annualSoftwareCost: 0 } },
  useCases: [{ title: 'Business Orders', description: 'Large print runs with deposits', example: '$8k/month saves $1,920/year', savings: '$1,920/year' }],
  industryFeatures: ['Quote Builder', 'Job Tracking', 'File Upload', 'Rush Pricing'],
  includedFeatures: [{ name: 'Job Management', description: 'Track print jobs', usualCost: '$40/mo' }],
  setupSteps: ['Connect wallet', 'Set pricing', 'Accept orders', 'Collect payment'],
  faqs: [{ question: 'Can customers upload files?', answer: 'Yes, accept file uploads with orders.' }],
  relatedIndustries: ['retail', 'photography-studios', 'freelancers'],
  relatedUseCases: ['b2b-payments', 'quote-invoicing'],
};

export const dryCleaners: IndustryLandingData = {
  slug: 'dry-cleaners',
  name: 'Dry Cleaners',
  icon: '👔',
  title: 'Crypto Payments for Dry Cleaners | 0.5-1% Fee | PortalPay',
  metaDescription: 'Dry cleaning payment processing. Pay only 0.5-1%. Track orders and manage customer accounts.',
  keywords: ['dry cleaner payments', 'laundry pos', 'dry cleaning crypto'],
  heroHeadline: 'Accept Crypto Payments for Dry Cleaning',
  heroSubheadline: 'Dry cleaners save 70% on fees. Customer accounts and order tracking included.',
  heroCTA: { primary: 'Start Free', primaryLink: '/admin', secondary: 'Try Demo', secondaryLink: '/terminal' },
  painPoints: ['Thin margins on services', 'Lost ticket tracking', 'Customer account management'],
  solutions: ['Lower fees, better margins', 'Digital order tracking', 'Customer profiles'],
  benefits: [
    { icon: '💰', title: 'Better Margins', description: 'Pay 0.5-1% vs 2.9%+', stat: '70% Savings' },
    { icon: '🎫', title: 'Order Tracking', description: 'Digital ticket system', stat: 'Included' },
  ],
  avgMonthlyVolume: 6000,
  competitorComparison: { square: { processingFee: 0.026, flatFee: 0.10, monthlyFee: 60, annualSoftwareCost: 720 } },
  useCases: [{ title: 'Regular Customers', description: 'Account-based billing', example: '$6k/month saves $1,440/year', savings: '$1,440/year' }],
  industryFeatures: ['Order Tracking', 'Customer Accounts', 'Price Lists', 'Pickup Reminders'],
  includedFeatures: [{ name: 'Ticket System', description: 'Digital order management', usualCost: '$50/mo' }],
  setupSteps: ['Connect wallet', 'Set service prices', 'Create orders', 'Collect on pickup'],
  faqs: [{ question: 'Can I track orders digitally?', answer: 'Yes, full digital ticket and tracking system.' }],
  relatedIndustries: ['laundromats', 'retail', 'salons'],
  relatedUseCases: ['account-billing', 'service-payments'],
};

export const laundromats: IndustryLandingData = {
  slug: 'laundromats',
  name: 'Laundromats',
  icon: '🧺',
  title: 'Crypto Payments for Laundromats | 0.5-1% Fee | PortalPay',
  metaDescription: 'Laundromat payment processing. Pay only 0.5-1%. Accept payments without coin machines.',
  keywords: ['laundromat payments', 'laundry crypto', 'washateria pos'],
  heroHeadline: 'Accept Crypto Payments at Your Laundromat',
  heroSubheadline: 'Go coinless with QR code payments. Save on processing and eliminate coin handling.',
  heroCTA: { primary: 'Start Free', primaryLink: '/admin', secondary: 'Try Demo', secondaryLink: '/terminal' },
  painPoints: ['Coin machine maintenance', 'Theft and vandalism', 'Cash handling costs'],
  solutions: ['QR code payments', 'No coin machines needed', 'Instant settlement'],
  benefits: [
    { icon: '💰', title: 'Eliminate Coins', description: 'No more coin machines', stat: 'Coinless' },
    { icon: '🔒', title: 'Reduce Theft', description: 'No cash on premises', stat: 'Secure' },
  ],
  avgMonthlyVolume: 10000,
  competitorComparison: { square: { processingFee: 0.026, flatFee: 0.10, monthlyFee: 0, annualSoftwareCost: 0 } },
  useCases: [{ title: 'Self-Service', description: 'QR codes on each machine', example: '$10k/month saves $2,400/year', savings: '$2,400/year' }],
  industryFeatures: ['Machine QR Codes', 'Usage Tracking', 'Loyalty Program', 'Remote Monitoring'],
  includedFeatures: [{ name: 'Machine Management', description: 'Track usage per machine', usualCost: '$100/mo' }],
  setupSteps: ['Connect wallet', 'Generate machine QR codes', 'Post at machines', 'Collect payments'],
  faqs: [{ question: 'Can each machine have its own QR?', answer: 'Yes, unique QR codes per machine with usage tracking.' }],
  relatedIndustries: ['dry-cleaners', 'retail', 'storage-facilities'],
  relatedUseCases: ['unattended-payments', 'qr-code-payments'],
};

export const storageFacilities: IndustryLandingData = {
  slug: 'storage-facilities',
  name: 'Storage Facilities',
  icon: '📦',
  title: 'Crypto Payments for Storage Units | 0.5-1% Fee | PortalPay',
  metaDescription: 'Self-storage payment processing. Pay only 0.5-1%. Automated billing and access control.',
  keywords: ['storage unit payments', 'self storage crypto', 'storage facility pos'],
  heroHeadline: 'Accept Crypto Payments for Storage',
  heroSubheadline: 'Storage facilities save 70% on recurring rent collection. Automated billing included.',
  heroCTA: { primary: 'Start Free', primaryLink: '/admin', secondary: 'Try Demo', secondaryLink: '/terminal' },
  painPoints: ['High recurring fees', 'Late payment chasing', 'Complex unit management'],
  solutions: ['0.5-1% on all rent', 'Auto-billing reminders', 'Unit tracking'],
  benefits: [
    { icon: '💰', title: 'Save on Rent Collection', description: '70% lower processing fees', stat: '70% Savings' },
    { icon: '🔄', title: 'Auto-Billing', description: 'Recurring payment reminders', stat: 'Included' },
  ],
  avgMonthlyVolume: 15000,
  competitorComparison: { stripe: { processingFee: 0.029, flatFee: 0.30, monthlyFee: 0, annualSoftwareCost: 0 } },
  useCases: [{ title: 'Monthly Rent', description: 'Automated rent collection', example: '$15k/month saves $3,600/year', savings: '$3,600/year' }],
  industryFeatures: ['Unit Management', 'Recurring Billing', 'Late Fee Automation', 'Tenant Portal'],
  includedFeatures: [{ name: 'Tenant Portal', description: 'Self-service payments', usualCost: '$100/mo' }],
  setupSteps: ['Connect wallet', 'Add units', 'Set rates', 'Enable auto-billing'],
  faqs: [{ question: 'Can rent be auto-billed?', answer: 'Yes, set up recurring billing with automatic reminders.' }],
  relatedIndustries: ['parking-lots', 'real-estate', 'moving-companies'],
  relatedUseCases: ['recurring-payments', 'property-management'],
};

export const parkingLots: IndustryLandingData = {
  slug: 'parking-lots',
  name: 'Parking Lots',
  icon: '🅿️',
  title: 'Crypto Payments for Parking | 0.5-1% Fee | PortalPay',
  metaDescription: 'Parking lot payment processing. Pay only 0.5-1%. QR code payments, no attendant needed.',
  keywords: ['parking payments', 'parking lot crypto', 'parking pos'],
  heroHeadline: 'Accept Crypto Payments for Parking',
  heroSubheadline: 'Parking operators save 70% on fees. QR code payments eliminate attendants.',
  heroCTA: { primary: 'Start Free', primaryLink: '/admin', secondary: 'Try Demo', secondaryLink: '/terminal' },
  painPoints: ['Attendant costs', 'Cash theft risk', 'Equipment maintenance'],
  solutions: ['Self-service QR payments', 'No cash handling', 'No expensive kiosks'],
  benefits: [
    { icon: '💰', title: 'Cut Labor Costs', description: 'QR payments, no attendants', stat: 'Unattended' },
    { icon: '📱', title: 'Mobile Payments', description: 'Customers scan and pay', stat: 'QR Based' },
  ],
  avgMonthlyVolume: 8000,
  competitorComparison: { square: { processingFee: 0.026, flatFee: 0.10, monthlyFee: 0, annualSoftwareCost: 0 } },
  useCases: [{ title: 'Daily Parking', description: 'QR codes at each entrance', example: '$8k/month saves $1,920/year', savings: '$1,920/year' }],
  industryFeatures: ['Zone Pricing', 'Time-Based Rates', 'Monthly Passes', 'Validation System'],
  includedFeatures: [{ name: 'Lot Management', description: 'Multi-zone support', usualCost: '$150/mo' }],
  setupSteps: ['Connect wallet', 'Set zone prices', 'Print QR signs', 'Go live'],
  faqs: [{ question: 'Can I have different rates per zone?', answer: 'Yes, set different pricing for each area.' }],
  relatedIndustries: ['storage-facilities', 'real-estate', 'gyms'],
  relatedUseCases: ['unattended-payments', 'qr-code-payments'],
};

export const carWashes: IndustryLandingData = {
  slug: 'car-washes',
  name: 'Car Washes',
  icon: '🚗',
  title: 'Crypto Payments for Car Washes | 0.5-1% Fee | PortalPay',
  metaDescription: 'Car wash payment processing. Pay only 0.5-1%. QR code payments for self-service or full-service.',
  keywords: ['car wash payments', 'auto detailing crypto', 'car wash pos'],
  heroHeadline: 'Accept Crypto Payments for Car Washes',
  heroSubheadline: 'Car washes save 70% on fees. QR codes work for self-service and full-service.',
  heroCTA: { primary: 'Start Free', primaryLink: '/admin', secondary: 'Try Demo', secondaryLink: '/terminal' },
  painPoints: ['Equipment costs', 'Cash handling issues', 'Membership management'],
  solutions: ['Low-cost QR payments', 'Cashless operation', 'Subscription billing'],
  benefits: [
    { icon: '💰', title: 'Go Cashless', description: 'QR payments at each bay', stat: 'No Cash' },
    { icon: '🔄', title: 'Memberships', description: 'Unlimited wash subscriptions', stat: 'Recurring' },
  ],
  avgMonthlyVolume: 12000,
  competitorComparison: { square: { processingFee: 0.026, flatFee: 0.10, monthlyFee: 0, annualSoftwareCost: 0 } },
  useCases: [{ title: 'Self-Service Bays', description: 'QR code at each bay', example: '$12k/month saves $2,880/year', savings: '$2,880/year' }],
  industryFeatures: ['Bay Management', 'Membership Plans', 'Package Deals', 'Loyalty Points'],
  includedFeatures: [{ name: 'Subscription System', description: 'Recurring wash passes', usualCost: '$75/mo' }],
  setupSteps: ['Connect wallet', 'Set wash prices', 'Post QR codes', 'Accept payments'],
  faqs: [{ question: 'Can I sell monthly memberships?', answer: 'Yes, create unlimited wash subscriptions.' }],
  relatedIndustries: ['auto-repair', 'parking-lots', 'retail'],
  relatedUseCases: ['subscription-payments', 'unattended-payments'],
};

export const towingServices: IndustryLandingData = {
  slug: 'towing-services',
  name: 'Towing Services',
  icon: '🚛',
  title: 'Crypto Payments for Towing | 0.5-1% Fee | PortalPay',
  metaDescription: 'Towing company payment processing. Pay only 0.5-1%. Accept roadside payments instantly.',
  keywords: ['towing payments', 'roadside assistance crypto', 'tow truck pos'],
  heroHeadline: 'Accept Crypto Payments for Towing',
  heroSubheadline: 'Towing companies get paid on the spot. No more chasing payments.',
  heroCTA: { primary: 'Start Free', primaryLink: '/admin', secondary: 'Try Demo', secondaryLink: '/terminal' },
  painPoints: ['Collecting payment on scene', 'Late invoice payments', 'Cash safety concerns'],
  solutions: ['QR payment on the spot', 'Instant settlement', 'No cash needed'],
  benefits: [
    { icon: '💰', title: 'Get Paid Immediately', description: 'QR payment before unhooking', stat: 'Instant' },
    { icon: '📱', title: 'Mobile Invoicing', description: 'Bill from your phone', stat: 'On-Site' },
  ],
  avgMonthlyVolume: 15000,
  competitorComparison: { square: { processingFee: 0.026, flatFee: 0.10, monthlyFee: 0, annualSoftwareCost: 0 } },
  useCases: [{ title: 'Roadside Tows', description: 'QR code payment before release', example: '$15k/month saves $3,600/year', savings: '$3,600/year' }],
  industryFeatures: ['Mobile Invoicing', 'Service Pricing', 'Mileage Rates', 'After-Hours Rates'],
  includedFeatures: [{ name: 'Mobile App', description: 'Invoice from anywhere', usualCost: '$50/mo' }],
  setupSteps: ['Connect wallet', 'Set service rates', 'Download app', 'Collect on scene'],
  faqs: [{ question: 'Can drivers collect payment on scene?', answer: 'Yes, generate QR codes from any phone.' }],
  relatedIndustries: ['auto-repair', 'parking-lots', 'plumbing-services'],
  relatedUseCases: ['mobile-payments', 'service-payments'],
};

export const movingCompanies: IndustryLandingData = {
  slug: 'moving-companies',
  name: 'Moving Companies',
  icon: '📦',
  title: 'Crypto Payments for Movers | 0.5-1% Fee | PortalPay',
  metaDescription: 'Moving company payment processing. Pay only 0.5-1%. Accept deposits and final payments easily.',
  keywords: ['moving company payments', 'movers crypto', 'moving service pos'],
  heroHeadline: 'Accept Crypto Payments for Moving Services',
  heroSubheadline: 'Moving companies save thousands on large job payments. Deposits and balances made easy.',
  heroCTA: { primary: 'Start Free', primaryLink: '/admin', secondary: 'Try Demo', secondaryLink: '/terminal' },
  painPoints: ['High fees on large moves', 'Deposit collection', 'On-site payment collection'],
  solutions: ['0.5-1% on all jobs', 'Easy deposit system', 'QR payment on delivery'],
  benefits: [
    { icon: '💰', title: 'Save on Big Jobs', description: '$3,000 move saves $72 vs Stripe', stat: '$72/job' },
    { icon: '📋', title: 'Quote System', description: 'Estimates to invoices', stat: 'Included' },
  ],
  avgMonthlyVolume: 25000,
  competitorComparison: { stripe: { processingFee: 0.029, flatFee: 0.30, monthlyFee: 0, annualSoftwareCost: 0 } },
  useCases: [{ title: 'Residential Moves', description: 'Deposit + balance on delivery', example: '$25k/month saves $6,000/year', savings: '$6,000/year' }],
  industryFeatures: ['Quote Builder', 'Inventory Lists', 'Deposit Tracking', 'Crew Management'],
  includedFeatures: [{ name: 'Estimating Tool', description: 'Room-by-room quotes', usualCost: '$100/mo' }],
  setupSteps: ['Connect wallet', 'Set rates', 'Create estimates', 'Collect deposits'],
  faqs: [{ question: 'Can I collect balance on delivery?', answer: 'Yes, crews can generate QR payment on site.' }],
  relatedIndustries: ['storage-facilities', 'cleaning-services', 'general-contractors'],
  relatedUseCases: ['high-value-transactions', 'deposit-payments'],
};

export const musicLessons: IndustryLandingData = {
  slug: 'music-lessons',
  name: 'Music Lessons',
  icon: '🎵',
  title: 'Crypto Payments for Music Teachers | 0.5-1% Fee | PortalPay',
  metaDescription: 'Music lesson payment processing. Pay only 0.5-1%. Free scheduling and student management.',
  keywords: ['music lesson payments', 'music teacher pos', 'instrument lessons crypto'],
  heroHeadline: 'Accept Crypto Payments for Music Lessons',
  heroSubheadline: 'Music teachers keep more of every lesson. Free scheduling included.',
  heroCTA: { primary: 'Start Free', primaryLink: '/admin', secondary: 'Try Demo', secondaryLink: '/terminal' },
  painPoints: ['Platform fees taking 15-20%', 'No-shows losing money', 'Scheduling headaches'],
  solutions: ['Keep 99%+ of earnings', 'Prepaid lessons reduce no-shows', 'Built-in scheduling'],
  benefits: [
    { icon: '💰', title: 'Keep More Money', description: 'Pay 0.5-1% vs platform 15-20%', stat: '95%+ Kept' },
    { icon: '📅', title: 'Free Scheduling', description: 'Students book online', stat: 'Included' },
  ],
  avgMonthlyVolume: 4000,
  competitorComparison: { stripe: { processingFee: 0.029, flatFee: 0.30, monthlyFee: 0, annualSoftwareCost: 0 } },
  useCases: [{ title: 'Weekly Lessons', description: 'Students pay per lesson or package', example: '$4k/month saves $960/year', savings: '$960/year' }],
  industryFeatures: ['Lesson Scheduling', 'Student Profiles', 'Progress Notes', 'Recital Management'],
  includedFeatures: [{ name: 'Booking System', description: 'Online lesson scheduling', usualCost: '$30/mo' }],
  setupSteps: ['Connect wallet', 'Set lesson rates', 'Share booking link', 'Teach and earn'],
  faqs: [{ question: 'Can students book lessons online?', answer: 'Yes, full self-service booking system.' }],
  relatedIndustries: ['tutoring-education', 'dance-studios', 'yoga-studios'],
  relatedUseCases: ['session-payments', 'recurring-payments'],
};

export const danceStudios: IndustryLandingData = {
  slug: 'dance-studios',
  name: 'Dance Studios',
  icon: '💃',
  title: 'Crypto Payments for Dance Studios | 0.5-1% Fee | PortalPay',
  metaDescription: 'Dance studio payment processing. Pay only 0.5-1%. Class registration and membership billing included.',
  keywords: ['dance studio payments', 'dance class pos', 'dance school crypto'],
  heroHeadline: 'Accept Crypto Payments for Dance Studios',
  heroSubheadline: 'Dance studios save 70% on tuition and class fees. Registration system included.',
  heroCTA: { primary: 'Start Free', primaryLink: '/admin', secondary: 'Try Demo', secondaryLink: '/terminal' },
  painPoints: ['High fees on recurring tuition', 'Class registration complexity', 'Costume/recital fee collection'],
  solutions: ['0.5-1% on all payments', 'Easy class registration', 'Event fee collection'],
  benefits: [
    { icon: '💰', title: 'Save on Tuition', description: 'Process $15k/month, save $3,600/year', stat: '$3,600/yr' },
    { icon: '📋', title: 'Class Registration', description: 'Online signup system', stat: 'Included' },
  ],
  avgMonthlyVolume: 15000,
  competitorComparison: { stripe: { processingFee: 0.029, flatFee: 0.30, monthlyFee: 0, annualSoftwareCost: 0 } },
  useCases: [{ title: 'Monthly Tuition', description: 'Recurring class payments', example: '$15k/month saves $3,600/year', savings: '$3,600/year' }],
  industryFeatures: ['Class Schedule', 'Student Registration', 'Recital Management', 'Costume Fees'],
  includedFeatures: [{ name: 'Registration System', description: 'Online class signup', usualCost: '$75/mo' }],
  setupSteps: ['Connect wallet', 'Add classes', 'Open registration', 'Collect tuition'],
  faqs: [{ question: 'Can parents register and pay online?', answer: 'Yes, full self-service registration and payment.' }],
  relatedIndustries: ['yoga-studios', 'martial-arts', 'gyms'],
  relatedUseCases: ['recurring-payments', 'class-registration'],
};

export const yogaStudios: IndustryLandingData = {
  slug: 'yoga-studios',
  name: 'Yoga Studios',
  icon: '🧘',
  title: 'Crypto Payments for Yoga Studios | 0.5-1% Fee | PortalPay',
  metaDescription: 'Yoga studio payment processing. Pay only 0.5-1%. Class passes, memberships, and drop-ins.',
  keywords: ['yoga studio payments', 'yoga class pos', 'wellness center crypto'],
  heroHeadline: 'Accept Crypto Payments for Yoga Studios',
  heroSubheadline: 'Yoga studios save 70% on class fees. Memberships and class passes included.',
  heroCTA: { primary: 'Start Free', primaryLink: '/admin', secondary: 'Try Demo', secondaryLink: '/terminal' },
  painPoints: ['High fees on recurring memberships', 'Class pass tracking', 'Drop-in management'],
  solutions: ['0.5-1% on all payments', 'Digital class passes', 'Easy membership billing'],
  benefits: [
    { icon: '💰', title: 'Save on Memberships', description: '70% lower processing fees', stat: '70% Savings' },
    { icon: '🎫', title: 'Class Passes', description: 'Digital punch cards', stat: 'Included' },
  ],
  avgMonthlyVolume: 12000,
  competitorComparison: { stripe: { processingFee: 0.029, flatFee: 0.30, monthlyFee: 0, annualSoftwareCost: 0 } },
  useCases: [{ title: 'Monthly Memberships', description: 'Unlimited class access', example: '$12k/month saves $2,880/year', savings: '$2,880/year' }],
  industryFeatures: ['Class Schedule', 'Memberships', 'Class Passes', 'Teacher Schedule'],
  includedFeatures: [{ name: 'Membership System', description: 'Recurring billing', usualCost: '$60/mo' }],
  setupSteps: ['Connect wallet', 'Add classes', 'Set membership tiers', 'Start accepting'],
  faqs: [{ question: 'Can I offer class passes?', answer: 'Yes, create 5-class, 10-class, or custom packages.' }],
  relatedIndustries: ['gyms', 'dance-studios', 'martial-arts'],
  relatedUseCases: ['membership-billing', 'class-passes'],
};

export const martialArts: IndustryLandingData = {
  slug: 'martial-arts',
  name: 'Martial Arts',
  icon: '🥋',
  title: 'Crypto Payments for Martial Arts | 0.5-1% Fee | PortalPay',
  metaDescription: 'Martial arts school payment processing. Pay only 0.5-1%. Membership billing and belt testing fees.',
  keywords: ['martial arts payments', 'dojo pos', 'karate school crypto'],
  heroHeadline: 'Accept Crypto Payments for Martial Arts Schools',
  heroSubheadline: 'Dojos and martial arts schools save 70% on tuition processing.',
  heroCTA: { primary: 'Start Free', primaryLink: '/admin', secondary: 'Try Demo', secondaryLink: '/terminal' },
  painPoints: ['High monthly tuition fees', 'Belt testing fee collection', 'Equipment sales processing'],
  solutions: ['0.5-1% on all payments', 'Easy fee collection', 'Built-in retail POS'],
  benefits: [
    { icon: '💰', title: 'Save on Tuition', description: '70% lower processing fees', stat: '70% Savings' },
    { icon: '🥋', title: 'Belt Testing', description: 'Collect testing fees easily', stat: 'Included' },
  ],
  avgMonthlyVolume: 10000,
  competitorComparison: { stripe: { processingFee: 0.029, flatFee: 0.30, monthlyFee: 0, annualSoftwareCost: 0 } },
  useCases: [{ title: 'Monthly Tuition', description: 'Family and individual plans', example: '$10k/month saves $2,400/year', savings: '$2,400/year' }],
  industryFeatures: ['Membership Billing', 'Belt Tracking', 'Testing Fees', 'Equipment Sales'],
  includedFeatures: [{ name: 'Student Management', description: 'Track belts and progress', usualCost: '$50/mo' }],
  setupSteps: ['Connect wallet', 'Set tuition rates', 'Add students', 'Start billing'],
  faqs: [{ question: 'Can I charge belt testing fees?', answer: 'Yes, one-time and recurring fees supported.' }],
  relatedIndustries: ['gyms', 'yoga-studios', 'dance-studios'],
  relatedUseCases: ['membership-billing', 'event-fees'],
};

export const bowlingAlleys: IndustryLandingData = {
  slug: 'bowling-alleys',
  name: 'Bowling Alleys',
  icon: '🎳',
  title: 'Crypto Payments for Bowling | 0.5-1% Fee | PortalPay',
  metaDescription: 'Bowling alley payment processing. Pay only 0.5-1%. Lane rentals, shoe rentals, and concessions.',
  keywords: ['bowling alley payments', 'bowling center pos', 'entertainment venue crypto'],
  heroHeadline: 'Accept Crypto Payments for Bowling',
  heroSubheadline: 'Bowling alleys save 70% on processing. Lane booking and POS included.',
  heroCTA: { primary: 'Start Free', primaryLink: '/admin', secondary: 'Try Demo', secondaryLink: '/terminal' },
  painPoints: ['Multiple revenue streams to track', 'Lane reservation management', 'High transaction fees'],
  solutions: ['All-in-one payment system', 'Lane booking included', '0.5-1% processing'],
  benefits: [
    { icon: '💰', title: 'Save on All Sales', description: 'Lanes, shoes, food, drinks', stat: '70% Savings' },
    { icon: '🎳', title: 'Lane Management', description: 'Online reservations', stat: 'Included' },
  ],
  avgMonthlyVolume: 20000,
  competitorComparison: { square: { processingFee: 0.026, flatFee: 0.10, monthlyFee: 60, annualSoftwareCost: 720 } },
  useCases: [{ title: 'Lane Rentals', description: 'Hourly lane booking and payment', example: '$20k/month saves $4,800/year', savings: '$4,800/year' }],
  industryFeatures: ['Lane Booking', 'Shoe Rental', 'Food & Beverage', 'Party Packages'],
  includedFeatures: [{ name: 'Reservation System', description: 'Online lane booking', usualCost: '$100/mo' }],
  setupSteps: ['Connect wallet', 'Set lane rates', 'Enable booking', 'Start accepting'],
  faqs: [{ question: 'Can customers book lanes online?', answer: 'Yes, full online reservation system.' }],
  relatedIndustries: ['arcades', 'escape-rooms', 'bars'],
  relatedUseCases: ['entertainment-payments', 'reservation-systems'],
};

export const escapeRooms: IndustryLandingData = {
  slug: 'escape-rooms',
  name: 'Escape Rooms',
  icon: '🔐',
  title: 'Crypto Payments for Escape Rooms | 0.5-1% Fee | PortalPay',
  metaDescription: 'Escape room payment processing. Pay only 0.5-1%. Online booking and group payments.',
  keywords: ['escape room payments', 'escape game pos', 'puzzle room crypto'],
  heroHeadline: 'Accept Crypto Payments for Escape Rooms',
  heroSubheadline: 'Escape rooms save 70% on booking fees. Online reservations included.',
  heroCTA: { primary: 'Start Free', primaryLink: '/admin', secondary: 'Try Demo', secondaryLink: '/terminal' },
  painPoints: ['High booking platform fees', 'Group payment complexity', 'No-show losses'],
  solutions: ['Direct booking, no platform fees', 'Easy group payments', 'Deposit system'],
  benefits: [
    { icon: '💰', title: 'Skip Platform Fees', description: 'Avoid 10-15% booking fees', stat: 'Direct Sales' },
    { icon: '📅', title: 'Online Booking', description: 'Customers book direct', stat: 'Included' },
  ],
  avgMonthlyVolume: 15000,
  competitorComparison: { stripe: { processingFee: 0.029, flatFee: 0.30, monthlyFee: 0, annualSoftwareCost: 0 } },
  useCases: [{ title: 'Room Bookings', description: 'Groups book and pay online', example: '$15k/month saves $3,600/year', savings: '$3,600/year' }],
  industryFeatures: ['Room Scheduling', 'Group Booking', 'Waiver Integration', 'Gift Cards'],
  includedFeatures: [{ name: 'Booking System', description: 'Multi-room scheduling', usualCost: '$100/mo' }],
  setupSteps: ['Connect wallet', 'Add rooms', 'Set time slots', 'Accept bookings'],
  faqs: [{ question: 'Can groups split payment?', answer: 'Yes, share booking link for group contributions.' }],
  relatedIndustries: ['arcades', 'bowling-alleys', 'event-planning'],
  relatedUseCases: ['booking-payments', 'group-payments'],
};

export const arcades: IndustryLandingData = {
  slug: 'arcades',
  name: 'Arcades',
  icon: '🕹️',
  title: 'Crypto Payments for Arcades | 0.5-1% Fee | PortalPay',
  metaDescription: 'Arcade payment processing. Pay only 0.5-1%. Game credits and play passes via QR code.',
  keywords: ['arcade payments', 'game center pos', 'arcade crypto'],
  heroHeadline: 'Accept Crypto Payments for Arcades',
  heroSubheadline: 'Arcades go cashless with QR payments. Credits and play passes included.',
  heroCTA: { primary: 'Start Free', primaryLink: '/admin', secondary: 'Try Demo', secondaryLink: '/terminal' },
  painPoints: ['Coin/token machine costs', 'Cash handling', 'Credit card minimums'],
  solutions: ['QR code game credits', 'Cashless operation', 'No minimums'],
  benefits: [
    { icon: '💰', title: 'Eliminate Tokens', description: 'Digital credits via QR', stat: 'Tokenless' },
    { icon: '🎮', title: 'Play Passes', description: 'Unlimited play packages', stat: 'Included' },
  ],
  avgMonthlyVolume: 18000,
  competitorComparison: { square: { processingFee: 0.026, flatFee: 0.10, monthlyFee: 0, annualSoftwareCost: 0 } },
  useCases: [{ title: 'Game Credits', description: 'Buy credits via QR code', example: '$18k/month saves $4,320/year', savings: '$4,320/year' }],
  industryFeatures: ['Credit System', 'Play Passes', 'Prize Redemption', 'Party Packages'],
  includedFeatures: [{ name: 'Credit Management', description: 'Digital game credits', usualCost: '$150/mo' }],
  setupSteps: ['Connect wallet', 'Set credit pricing', 'Post QR codes', 'Go cashless'],
  faqs: [{ question: 'Can customers buy credits with QR?', answer: 'Yes, instant digital credits via QR code.' }],
  relatedIndustries: ['bowling-alleys', 'escape-rooms', 'bars'],
  relatedUseCases: ['cashless-payments', 'credit-systems'],
};

export const movieTheaters: IndustryLandingData = {
  slug: 'movie-theaters',
  name: 'Movie Theaters',
  icon: '🎬',
  title: 'Crypto Payments for Movie Theaters | 0.5-1% Fee | PortalPay',
  metaDescription: 'Movie theater payment processing. Pay only 0.5-1%. Ticket sales and concessions.',
  keywords: ['movie theater payments', 'cinema pos', 'theater crypto'],
  heroHeadline: 'Accept Crypto Payments for Movie Theaters',
  heroSubheadline: 'Theaters save 70% on ticket and concession sales. Full POS included.',
  heroCTA: { primary: 'Start Free', primaryLink: '/admin', secondary: 'Try Demo', secondaryLink: '/terminal' },
  painPoints: ['High fees on ticket sales', 'Concession processing costs', 'Online ticketing fees'],
  solutions: ['0.5-1% on all sales', 'Free online ticketing', 'Integrated concessions'],
  benefits: [
    { icon: '💰', title: 'Save on Tickets', description: '70% lower processing', stat: '70% Savings' },
    { icon: '🎟️', title: 'Online Ticketing', description: 'No platform fees', stat: 'Free' },
  ],
  avgMonthlyVolume: 30000,
  competitorComparison: { square: { processingFee: 0.026, flatFee: 0.10, monthlyFee: 60, annualSoftwareCost: 720 } },
  useCases: [{ title: 'Ticket Sales', description: 'Online and box office', example: '$30k/month saves $7,200/year', savings: '$7,200/year' }],
  industryFeatures: ['Seat Selection', 'Showtime Management', 'Concession POS', 'Loyalty Program'],
  includedFeatures: [{ name: 'Ticketing System', description: 'Online seat selection', usualCost: '$200/mo' }],
  setupSteps: ['Connect wallet', 'Add showtimes', 'Enable online sales', 'Start selling'],
  faqs: [{ question: 'Can customers pick seats online?', answer: 'Yes, full seat selection system included.' }],
  relatedIndustries: ['arcades', 'bowling-alleys', 'event-planning'],
  relatedUseCases: ['ticketing', 'entertainment-payments'],
};
