import { loadEnv } from "../config/load-env";
import { connectDB } from "./connection";
import { User } from "../models/User";
import { TeamMember } from "../models/TeamMember";
import { Shift } from "../models/Shift";
import { Supplier } from "../models/Supplier";
import { InventoryItem } from "../models/InventoryItem";
import { InventoryTransaction } from "../models/InventoryTransaction";
import { PurchaseOrder } from "../models/PurchaseOrder";
import { ServicePackage } from "../models/ServicePackage";
import { ServiceBay } from "../models/ServiceBay";
import { ServiceLaneTicket } from "../models/ServiceLaneTicket";
import { AutomationAsset } from "../models/AutomationAsset";
import { Invoice } from "../models/Invoice";
import { Analytics } from "../models/Analytics";
import AIInsight from "../models/AIInsight";
import PerformanceEntry from "../models/PerformanceEntry";
import { format } from "date-fns";

function daysAgo(days: number): Date {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d;
}
async function seedDatabase() {
  try {
    loadEnv();
    console.log("?? Starting LedgerOne Auto Shop seed...");

    await connectDB();

    await Promise.all([
      User.deleteMany({}),
      TeamMember.deleteMany({}),
      Shift.deleteMany({}),
      Supplier.deleteMany({}),
      InventoryItem.deleteMany({}),
      InventoryTransaction.deleteMany({}),
      PurchaseOrder.deleteMany({}),
      ServicePackage.deleteMany({}),
      ServiceBay.deleteMany({}),
      ServiceLaneTicket.deleteMany({}),
      AutomationAsset.deleteMany({}),
      Invoice.deleteMany({}),
      Analytics.deleteMany({}),
      AIInsight.deleteMany({}),
      PerformanceEntry.deleteMany({}),
    ]);

    console.log("?? Cleared previous collections");

    const adminUser = await User.create({
      name: "Sky Service Director",
      email: "admin@ledgerauto.demo",
      role: "Super Admin",
      password: "hashedpassword123",
      permissions: [
        "dashboard",
        "scheduling",
        "inventory",
        "invoicing",
        "team",
        "analytics",
        "hostpro",
        "robotic-fleets",
        "settings",
      ],
    });

    const teamMembers = await TeamMember.insertMany([
      {
        name: "Jordan Reyes",
        email: "jordan.reyes@ledgerauto.demo",
        phone: "+1-470-555-0101",
        toastId: "toast-jordan-001",
        role: "Master Technician",
        department: "Service Bays",
        availability: "Full-time",
        hourlyRate: 38,
        skills: ["Hybrid diagnostics", "Powertrain rebuilds", "Advanced drivability"],
        certifications: ["ASE L1", "ASE A9"],
        performance: {
          rating: 4.8,
          completedShifts: 186,
          onTimeRate: 97,
          comebacks: 1,
          upsellCaptureRate: 42,
          aseCertifications: ["ASE L1", "ASE A1", "EV Specialist"],
        },
      },
      {
        name: "Maya Chen",
        email: "maya.chen@ledgerauto.demo",
        phone: "+1-470-555-0102",
        toastId: "toast-maya-002",
        role: "Diagnostic Specialist",
        department: "Diagnostics",
        availability: "Full-time",
        hourlyRate: 44,
        skills: ["Oscilloscope mastery", "ADAS calibration", "Network tracing"],
        certifications: ["ASE L2", "ADAS Level 3"],
        performance: {
          rating: 4.9,
          completedShifts: 172,
          onTimeRate: 99,
          comebacks: 0,
          upsellCaptureRate: 35,
          aseCertifications: ["ASE L2", "ASE A6"],
        },
      },
      {
        name: "Evan Martinez",
        email: "evan.martinez@ledgerauto.demo",
        phone: "+1-470-555-0103",
        toastId: "toast-evan-003",
        role: "Service Advisor",
        department: "Front Desk",
        availability: "Full-time",
        hourlyRate: 29,
        skills: ["Customer communication", "Digital inspections", "Warranty approvals"],
        certifications: ["ASE Service Consultant"],
        performance: {
          rating: 4.6,
          completedShifts: 198,
          onTimeRate: 94,
          comebacks: 0,
          upsellCaptureRate: 57,
          aseCertifications: ["Service Consultant"],
        },
      },
      {
        name: "Priya Kapoor",
        email: "priya.kapoor@ledgerauto.demo",
        phone: "+1-470-555-0104",
        toastId: "toast-priya-004",
        role: "Parts Specialist",
        department: "Parts",
        availability: "Full-time",
        hourlyRate: 25,
        skills: ["OE cataloging", "Vendor negotiation", "Express staging"],
        certifications: [],
        performance: {
          rating: 4.7,
          completedShifts: 204,
          onTimeRate: 98,
          comebacks: 0,
          upsellCaptureRate: 21,
          aseCertifications: [],
        },
      },
      {
        name: "Hector Alvarez",
        email: "hector.alvarez@ledgerauto.demo",
        phone: "+1-470-555-0105",
        toastId: "toast-hector-005",
        role: "EV & Battery Tech",
        department: "Service Bays",
        availability: "Full-time",
        hourlyRate: 41,
        skills: ["High-voltage troubleshooting", "HV battery rebuilds", "Thermal management"],
        certifications: ["EV Level 3", "ASE A6"],
        performance: {
          rating: 4.8,
          completedShifts: 160,
          onTimeRate: 96,
          comebacks: 0,
          upsellCaptureRate: 38,
          aseCertifications: ["ASE A6"],
        },
      },
      {
        name: "Noelle Rivers",
        email: "noelle.rivers@ledgerauto.demo",
        phone: "+1-470-555-0106",
        toastId: "toast-noelle-006",
        role: "Express Technician",
        department: "Service Bays",
        availability: "Full-time",
        hourlyRate: 23,
        skills: ["Oil services", "Brake service", "Alignment checks"],
        certifications: ["ASE A5"],
        performance: {
          rating: 4.4,
          completedShifts: 132,
          onTimeRate: 92,
          comebacks: 2,
          upsellCaptureRate: 29,
          aseCertifications: ["ASE A5"],
        },
      },
      {
        name: "Kyla Moore",
        email: "kyla.moore@ledgerauto.demo",
        phone: "+1-470-555-0107",
        toastId: "toast-kyla-007",
        role: "Detail Lead",
        department: "Detail",
        availability: "Part-time",
        hourlyRate: 19,
        skills: ["Ceramic coatings", "Interior restorations"],
        certifications: [],
        performance: {
          rating: 4.5,
          completedShifts: 102,
          onTimeRate: 95,
          comebacks: 0,
          upsellCaptureRate: 18,
          aseCertifications: [],
        },
      },
      {
        name: "Gideon Clark",
        email: "gideon.clark@ledgerauto.demo",
        phone: "+1-470-555-0108",
        toastId: "toast-gideon-008",
        role: "Field Service Technician",
        department: "Field Service",
        availability: "On-call",
        hourlyRate: 36,
        skills: ["Fleet mobile repairs", "Emergency diagnostics"],
        certifications: ["ASE A9"],
        performance: {
          rating: 4.3,
          completedShifts: 88,
          onTimeRate: 90,
          comebacks: 1,
          upsellCaptureRate: 12,
          aseCertifications: ["ASE A9"],
        },
      },
    ]);
    const shifts = await Shift.insertMany([
      {
        date: daysAgo(1),
        startTime: "08:00",
        endTime: "17:00",
        role: "Diagnostic Specialist",
        assignedTo: teamMembers[1]._id,
        status: "completed",
        notes: "Handled EV thermal management diagnosis",
        breakTime: 30,
        createdBy: adminUser._id,
      },
      {
        date: new Date(),
        startTime: "09:00",
        endTime: "18:00",
        role: "Master Technician",
        assignedTo: teamMembers[0]._id,
        status: "active",
        notes: "Engine timing chain & ADAS recalibration",
        breakTime: 30,
        createdBy: adminUser._id,
      },
      {
        date: new Date(),
        startTime: "07:00",
        endTime: "16:00",
        role: "Service Advisor",
        assignedTo: teamMembers[2]._id,
        status: "active",
        notes: "Morning drop-off surge",
        breakTime: 45,
        createdBy: adminUser._id,
      },
    ]);
    const suppliers = await Supplier.insertMany([
      {
        name: "Metro OEM Parts",
        companyName: "Metro OEM Distribution",
        supplierCode: "OEM-METRO",
        type: "OEM",
        categories: ["Powertrain", "Electrical", "HVAC"],
        status: "active",
        contacts: [
          { name: "Daniel Price", email: "daniel@metrooem.demo", phone: "+1-470-555-2101", isPrimary: true },
        ],
        logistics: { deliveryDays: ["Monday", "Wednesday", "Friday"], leadTimeDays: 1 },
        preferred: true,
        createdBy: adminUser._id,
      },
      {
        name: "TorqueFlow Aftermarket",
        companyName: "TorqueFlow Supply",
        supplierCode: "AF-TORQUE",
        type: "Aftermarket",
        categories: ["Suspension", "Braking", "Accessories"],
        status: "active",
        contacts: [
          { name: "Jamie Ortega", email: "jamie@torqueflow.demo", phone: "+1-470-555-2102", isPrimary: true },
        ],
        logistics: { deliveryDays: ["Tuesday", "Thursday"], leadTimeDays: 2 },
        createdBy: adminUser._id,
      },
      {
        name: "Energex EV Systems",
        companyName: "Energex Components",
        supplierCode: "EV-ENERGEX",
        type: "Aftermarket",
        categories: ["Electrical", "Diagnostics"],
        status: "active",
        contacts: [
          { name: "Lena Brooks", email: "lena@energex.demo", phone: "+1-470-555-2103", isPrimary: true },
        ],
        logistics: { deliveryDays: ["Monday", "Thursday"], leadTimeDays: 3 },
        createdBy: adminUser._id,
      },
      {
        name: "FleetSafe Fluids",
        companyName: "FleetSafe Industrial",
        supplierCode: "FS-FLUIDS",
        type: "Fluids & Chemicals",
        categories: ["Fluids", "Shop Supplies"],
        status: "active",
        contacts: [
          { name: "Omar Simmons", email: "omar@fleetsafe.demo", phone: "+1-470-555-2104", isPrimary: true },
        ],
        logistics: { deliveryDays: ["Friday"], leadTimeDays: 5 },
        createdBy: adminUser._id,
      },
      {
        name: "Precision Brake Labs",
        companyName: "Precision Components Inc.",
        supplierCode: "PB-BRAKES",
        type: "Aftermarket",
        categories: ["Braking"],
        status: "active",
        contacts: [
          { name: "Carmen Lee", email: "carmen@precisionbrake.demo", phone: "+1-470-555-2105", isPrimary: true },
        ],
        logistics: { deliveryDays: ["Wednesday"], leadTimeDays: 2 },
        createdBy: adminUser._id,
      },
      {
        name: "Northway Tires",
        companyName: "Northway Tire Distribution",
        supplierCode: "NW-TIRES",
        type: "Tire Distributor",
        categories: ["Tires"],
        status: "active",
        contacts: [
          { name: "Silvia Fox", email: "silvia@northway.demo", phone: "+1-470-555-2106", isPrimary: true },
        ],
        logistics: { deliveryDays: ["Monday", "Thursday"], leadTimeDays: 1, expeditedLeadTimeDays: 0 },
        createdBy: adminUser._id,
      },
    ]);

    const inventoryItems = await InventoryItem.insertMany([

      {
        name: "Ceramic Brake Pad Kit - Front",
        category: "Braking",
        partNumber: "CBP-2045F",
        brand: "Precision Brake Labs",
        manufacturer: "Precision Brake Labs",
        unit: "set",
        currentStock: 22,
        minThreshold: 6,
        reorderPoint: 10,
        reorderQuantity: 12,
        safetyStock: 4,
        maxCapacity: 40,
        costPerUnit: 68.5,
        msrp: 139.99,
        warrantyMonths: 24,
        supplier: suppliers[4]._id,
        supplierName: suppliers[4].name,
        leadTimeDays: 2,
        segment: "OE Equivalent",
        vehicleSystems: ["Braking"],
        compatibility: [
          { make: "Toyota", models: ["Camry", "Avalon"], years: [2018, 2019, 2020, 2021, 2022] },
        ],
        createdBy: adminUser._id,
      },
      {
        name: "ProTorque Coilover Assembly",
        category: "Suspension",
        partNumber: "PT-SUS-881",
        brand: "TorqueFlow",
        manufacturer: "TorqueFlow",
        unit: "each",
        currentStock: 10,
        minThreshold: 4,
        reorderPoint: 6,
        reorderQuantity: 8,
        safetyStock: 2,
        maxCapacity: 20,
        costPerUnit: 220,
        msrp: 449.99,
        supplier: suppliers[1]._id,
        supplierName: suppliers[1].name,
        leadTimeDays: 2,
        compatibility: [
          { make: "Subaru", models: ["WRX", "STI"], years: [2015, 2016, 2017, 2018, 2019] },
        ],
        createdBy: adminUser._id,
      },
      {
        name: "OEM Timing Chain Kit",
        category: "Powertrain",
        partNumber: "OEM-TCK-GM23",
        brand: "Metro OEM",
        manufacturer: "Metro OEM",
        unit: "kit",
        currentStock: 6,
        minThreshold: 2,
        reorderPoint: 3,
        reorderQuantity: 4,
        safetyStock: 2,
        maxCapacity: 12,
        costPerUnit: 415,
        msrp: 799.99,
        supplier: suppliers[0]._id,
        supplierName: suppliers[0].name,
        leadTimeDays: 1,
        segment: "OEM",
        compatibility: [
          { make: "GM", models: ["Impala", "Traverse"], years: [2016, 2017, 2018, 2019] },
        ],
        createdBy: adminUser._id,
      },
      {
        name: "HV Battery Module - 12 Cell",
        category: "Electrical",
        partNumber: "EV-HVB-12",
        brand: "Energex",
        manufacturer: "Energex",
        unit: "module",
        currentStock: 4,
        minThreshold: 2,
        reorderPoint: 3,
        reorderQuantity: 4,
        safetyStock: 2,
        maxCapacity: 12,
        costPerUnit: 690,
        msrp: 1099.99,
        warrantyMonths: 36,
        supplier: suppliers[2]._id,
        supplierName: suppliers[2].name,
        leadTimeDays: 3,
        segment: "Performance",
        compatibility: [{ make: "Hyundai", models: ["IONIQ"], years: [2019, 2020, 2021] }],
        createdBy: adminUser._id,
      },
      {
        name: "ADAS Calibration Target Kit",
        category: "Diagnostics",
        partNumber: "ADAS-TGT-Pro",
        brand: "Energex",
        manufacturer: "Energex",
        unit: "kit",
        currentStock: 2,
        minThreshold: 1,
        reorderPoint: 1,
        reorderQuantity: 1,
        safetyStock: 1,
        maxCapacity: 5,
        costPerUnit: 1280,
        msrp: 1999.99,
        supplier: suppliers[2]._id,
        supplierName: suppliers[2].name,
        leadTimeDays: 4,
        segment: "Performance",
        createdBy: adminUser._id,
      },
      {
        name: "FleetSafe Dexos Oil 5W-30",
        category: "Fluids",
        partNumber: "FS-5W30-DX",
        brand: "FleetSafe",
        manufacturer: "FleetSafe",
        unit: "case",
        currentStock: 32,
        minThreshold: 12,
        reorderPoint: 16,
        reorderQuantity: 24,
        safetyStock: 8,
        maxCapacity: 60,
        costPerUnit: 46,
        msrp: 89.99,
        supplier: suppliers[3]._id,
        supplierName: suppliers[3].name,
        leadTimeDays: 5,
        segment: "OE Equivalent",
        createdBy: adminUser._id,
      },
      {
        name: "Aluminum Performance Radiator",
        category: "Powertrain",
        partNumber: "TPR-CoolX",
        brand: "TorqueFlow",
        manufacturer: "TorqueFlow",
        unit: "each",
        currentStock: 8,
        minThreshold: 3,
        reorderPoint: 4,
        reorderQuantity: 6,
        safetyStock: 2,
        maxCapacity: 18,
        costPerUnit: 185,
        msrp: 349.99,
        supplier: suppliers[1]._id,
        supplierName: suppliers[1].name,
        leadTimeDays: 2,
        createdBy: adminUser._id,
      },
      {
        name: "Alignment Adjustment Shim Kit",
        category: "Suspension",
        partNumber: "ALIGN-SMK-55",
        brand: "TorqueFlow",
        manufacturer: "TorqueFlow",
        unit: "pack",
        currentStock: 34,
        minThreshold: 10,
        reorderPoint: 16,
        reorderQuantity: 20,
        safetyStock: 6,
        maxCapacity: 60,
        costPerUnit: 22,
        msrp: 49.99,
        supplier: suppliers[1]._id,
        supplierName: suppliers[1].name,
        leadTimeDays: 1,
        createdBy: adminUser._id,
      },
      {
        name: "Premium Cabin Air Filter",
        category: "HVAC",
        partNumber: "OEM-CAB-XL",
        brand: "Metro OEM",
        manufacturer: "Metro OEM",
        unit: "each",
        currentStock: 120,
        minThreshold: 40,
        reorderPoint: 60,
        reorderQuantity: 80,
        safetyStock: 30,
        maxCapacity: 200,
        costPerUnit: 11.5,
        msrp: 29.99,
        supplier: suppliers[0]._id,
        supplierName: suppliers[0].name,
        leadTimeDays: 1,
        createdBy: adminUser._id,
      },
      {
        name: "Dual Action Polishing Pad Kit",
        category: "Detailing",
        partNumber: "DL-DA-PAD",
        brand: "ShineCraft",
        manufacturer: "ShineCraft",
        unit: "kit",
        currentStock: 20,
        minThreshold: 6,
        reorderPoint: 8,
        reorderQuantity: 12,
        safetyStock: 4,
        maxCapacity: 30,
        costPerUnit: 34,
        msrp: 79.99,
        supplierName: "ShineCraft Lab",
        leadTimeDays: 4,
        createdBy: adminUser._id,
      },
    ]);
    const servicePackages = await ServicePackage.insertMany([
      {
        serviceCode: "A-SVC-1001",
        name: "Hybrid Powertrain Inspection",
        shortName: "Hybrid Inspection",
        category: "Diagnostics",
        subcategory: "Hybrid systems",
        description: "Full hybrid system integrity inspection including high-voltage isolation test, thermal profile analysis, and software calibration sync.",
        detailedSteps: [
          "Pull DTC history and freeze frame data",
          "Perform high-voltage isolation and thermal stability test",
          "Review inverter and battery cooling loops",
          "Update hybrid control software to latest calibration",
          "Document predictive wear with photos and diagnostics report",
        ],
        laborHours: 3.5,
        basePrice: 465,
        bayType: "Diagnostic",
        skillLevel: "Advanced",
        warrantyMonths: 6,
        serviceIntervalMiles: 15000,
        serviceIntervalMonths: 12,
        sameDayEligible: false,
        isSeasonal: false,
        isFeatured: true,
        safetyNotes: "Verify HV disconnect before commencing work. Use arc-rated PPE.",
        requiredEquipment: ["EV isolation tester", "Thermal imaging camera", "OEM scan tool"],
        upsellRecommendations: ["HV battery reconditioning", "Inverter coolant flush"],
        inspectionChecklist: ["High voltage cable condition", "Battery module balancing health", "Power electronics leak check"],
        recommendedParts: [
          { part: inventoryItems[3]._id, quantity: 1, unit: "module", note: "Replace if module resistance delta > 15%" },
          { part: inventoryItems[5]._id, quantity: 2, unit: "case", note: "Battery coolant top-off as needed" },
        ],
        createdBy: adminUser._id,
      },
      {
        serviceCode: "A-SVC-1020",
        name: "Precision Brake Refresh",
        shortName: "Brake Refresh",
        category: "Braking",
        description: "Two-axle brake service with ceramic pad upgrade, rotor resurfacing, caliper slide restoration, and post-road test bedding.",
        detailedSteps: [
          "Inspect braking system, measure rotor runout",
          "Resurface or replace rotors to spec",
          "Install ceramic pad kit with proper bedding procedure",
          "Flush brake fluid and bleed system",
          "Road test with thermal scan verification",
        ],
        laborHours: 2.8,
        basePrice: 389,
        bayType: "General",
        skillLevel: "Intermediate",
        warrantyMonths: 24,
        sameDayEligible: true,
        isSeasonal: false,
        requiredEquipment: ["Brake lathe", "Thermal scanner"],
        upsellRecommendations: ["Brake fluid moisture test kit", "Ceramic pad break-in kit"],
        inspectionChecklist: ["Rotor thickness", "Caliper slide movement", "Brake hose flex"],
        recommendedParts: [
          { part: inventoryItems[0]._id, quantity: 1, unit: "set", note: "CBP Ceramic pads" },
          { part: inventoryItems[5]._id, quantity: 1, unit: "case", note: "Brake fluid flush kit" },
        ],
        createdBy: adminUser._id,
      },
      {
        serviceCode: "A-SVC-1044",
        name: "Performance Suspension Overhaul",
        shortName: "Suspension Overhaul",
        category: "Suspension",
        description: "Complete suspension refresh with coilover upgrade, alignment, and chassis torque audit for performance vehicles.",
        detailedSteps: [
          "Baseline suspension measurements and alignment check",
          "Install new coilovers and components",
          "Torque chassis to manufacturer spec with digital logging",
          "Conduct performance road calibration",
        ],
        laborHours: 5.5,
        basePrice: 960,
        bayType: "Heavy Duty",
        skillLevel: "Advanced",
        warrantyMonths: 12,
        sameDayEligible: false,
        requiredEquipment: ["Four-post lift", "Corner balancing scales"],
        upsellRecommendations: ["Alignment shim kit", "Chassis stiffening brace"],
        inspectionChecklist: ["Bushing condition", "Corner weight balance", "Ride height calibration"],
        recommendedParts: [
          { part: inventoryItems[1]._id, quantity: 4, unit: "each", note: "Complete coilover assemblies" },
          { part: inventoryItems[7]._id, quantity: 2, unit: "pack", note: "Alignment shims for fine tuning" },
        ],
        createdBy: adminUser._id,
      },
      {
        serviceCode: "A-SVC-2035",
        name: "Fleet Express Service",
        shortName: "Fleet Express",
        category: "Fleet Service",
        description: "12-point fleet service with oil change, brake inspection, telematics scan, and DOT safety review.",
        detailedSteps: ["Perform multi-point inspection", "Change oil and filters", "Update telematics logs", "Document DOT checklist"],
        laborHours: 1.8,
        basePrice: 189,
        bayType: "Express",
        skillLevel: "Apprentice",
        warrantyMonths: 3,
        sameDayEligible: true,
        requiredEquipment: ["Fleet diagnostic scanner"],
        upsellRecommendations: ["Brake fluid test", "Battery load test"],
        inspectionChecklist: ["Lighting compliance", "Brake lining depth", "Fluid leaks"],
        recommendedParts: [
          { part: inventoryItems[5]._id, quantity: 1, unit: "case", note: "Oil and filters" },
          { part: inventoryItems[8]._id, quantity: 1, unit: "each", note: "Cabin filter for driver comfort" },
        ],
        createdBy: adminUser._id,
      },
      {
        serviceCode: "A-SVC-3020",
        name: "EV Thermal Management Rebuild",
        shortName: "EV Thermal Service",
        category: "HVAC",
        description: "Rebuild EV thermal loops including coolant flush, chiller inspection, and software adaptation reset.",
        detailedSteps: ["Drain and pressure test thermal loop", "Inspect chiller and pumps", "Refill with OEM coolant", "Run adaptation reset"],
        laborHours: 3.1,
        basePrice: 495,
        bayType: "EV Specialized",
        skillLevel: "Advanced",
        warrantyMonths: 12,
        sameDayEligible: false,
        requiredEquipment: ["Vacuum fill system", "OEM EV scan tool"],
        upsellRecommendations: ["Battery module balancing", "Inverter inspection"],
        inspectionChecklist: ["Coolant purity", "Chiller performance", "Thermal pump noise"],
        recommendedParts: [
          { part: inventoryItems[5]._id, quantity: 2, unit: "case", note: "Dexos EV coolant" },
        ],
        createdBy: adminUser._id,
      },
      {
        serviceCode: "A-SVC-4005",
        name: "Concours-Level Detail & Ceramic Coating",
        shortName: "Concours Detail",
        category: "Detailing",
        description: "Multi-stage paint correction, ceramic coating, interior restorative detail, and delivery presentation.",
        detailedSteps: ["Paint decontamination", "Dual-stage correction", "Apply ceramic coating", "Interior restorative detail"],
        laborHours: 6.5,
        basePrice: 720,
        bayType: "Detail",
        skillLevel: "Advanced",
        warrantyMonths: 24,
        sameDayEligible: false,
        requiredEquipment: ["Infrared curing lamps"],
        upsellRecommendations: ["Wheel ceramic coating", "Glass protection"],
        inspectionChecklist: ["Paint clarity", "Interior odor neutralization"],
        recommendedParts: [
          { part: inventoryItems[9]._id, quantity: 1, unit: "kit", note: "Polishing pad kit" },
        ],
        createdBy: adminUser._id,
      },
    ]);
    const serviceBays = await ServiceBay.insertMany([
      {
        label: "Bay A1",
        type: "General",
        status: "occupied",
        capacity: 1,
        queueDepth: 1,
        features: ["Two-post lift", "Brake lathe"],
        createdBy: adminUser._id,
      },
      {
        label: "Bay B2",
        type: "Diagnostic",
        status: "available",
        capacity: 1,
        queueDepth: 0,
        features: ["EV isolation station", "ADAS calibration rig"],
        createdBy: adminUser._id,
      },
      {
        label: "Bay EV-1",
        type: "EV Specialized",
        status: "available",
        capacity: 1,
        queueDepth: 0,
        features: ["High-voltage platform", "Battery lift"],
        createdBy: adminUser._id,
      },
      {
        label: "Bay Express",
        type: "Express",
        status: "reserved",
        capacity: 2,
        queueDepth: 2,
        features: ["Quick-lube pit", "Fleet telematics"],
        createdBy: adminUser._id,
      },
    ]);
    const serviceTickets = await ServiceLaneTicket.insertMany([
      {
        ticketNumber: "RO-84521",
        customerName: "Taylor Jennings",
        customerContact: { phone: "+1-470-555-2201", email: "taylor.jennings@example.com", prefersText: true },
        vehicle: { vin: "5NMS3CADXLH015847", year: 2020, make: "Hyundai", model: "Santa Fe", mileageIn: 45210 },
        services: [
          { servicePackage: servicePackages[0]._id, status: "diagnosing", estimatedHours: 3.5, estimatedPrice: 465, approved: true },
          { servicePackage: servicePackages[4]._id, status: "waiting_parts", estimatedHours: 3.1, estimatedPrice: 495, approved: true },
        ],
        advisor: teamMembers[2]._id,
        primaryTechnician: teamMembers[1]._id,
        bay: serviceBays[1]._id,
        status: "waiting_parts",
        dropoffTime: daysAgo(1),
        promisedTime: daysAgo(-1),
        notes: [{ author: "Service Advisor", message: "Customer approved HV battery module replacement.", kind: "advisor" }],
        recommendedFollowUps: ["Battery reconditioning in 6 months"],
        createdBy: adminUser._id,
      },
      {
        ticketNumber: "RO-84522",
        customerName: "Zen Fleet Services",
        customerContact: { phone: "+1-470-555-2202", email: "maintenance@zenfleet.demo", prefersText: false },
        vehicle: { vin: "1FT8W3BT6MEC21045", year: 2019, make: "Ford", model: "F-350", mileageIn: 92800 },
        services: [
          { servicePackage: servicePackages[3]._id, status: "in_progress", estimatedHours: 1.8, actualHours: 0.5, estimatedPrice: 189, approved: true },
        ],
        advisor: teamMembers[2]._id,
        primaryTechnician: teamMembers[5]._id,
        bay: serviceBays[3]._id,
        status: "in_service",
        dropoffTime: daysAgo(0),
        promisedTime: daysAgo(-1),
        createdBy: adminUser._id,
      },
      {
        ticketNumber: "RO-84523",
        customerName: "Vanessa Liu",
        customerContact: { phone: "+1-470-555-2203", email: "vanessa.liu@example.com", prefersText: true },
        vehicle: { vin: "JTDKN3DU2A1234567", year: 2017, make: "Toyota", model: "Prius", mileageIn: 121500 },
        services: [
          { servicePackage: servicePackages[1]._id, status: "completed", actualHours: 2.7, estimatedPrice: 389, approved: true },
        ],
        advisor: teamMembers[2]._id,
        primaryTechnician: teamMembers[0]._id,
        bay: serviceBays[0]._id,
        status: "ready_for_pickup",
        dropoffTime: daysAgo(2),
        promisedTime: daysAgo(0),
        createdBy: adminUser._id,
      },
    ]);
    const automationAssets = await AutomationAsset.insertMany([
      {
        name: "Atlas Autonomous Tool Cart #1",
        type: "Autonomous Tool Cart",
        status: "online",
        zone: "Service Core",
        assignedBay: serviceBays[0]._id,
        manufacturer: "Atlas Robotics",
        modelNumber: "ATC-500",
        utilizationRate: 82,
        firmwareVersion: "v5.3.1",
        connectedDevices: 4,
        lastHeartbeat: new Date(),
        lastServiceDate: daysAgo(25),
        nextServiceDate: daysAgo(-5),
        createdBy: adminUser._id,
      },
      {
        name: "Bolt EV Charger 180kW",
        type: "EV Charger",
        status: "maintenance",
        zone: "EV Pod",
        assignedBay: serviceBays[2]._id,
        manufacturer: "BoltGrid",
        modelNumber: "BoltGrid-180",
        utilizationRate: 64,
        firmwareVersion: "v3.8.4",
        connectedDevices: 1,
        lastHeartbeat: new Date(),
        lastServiceDate: daysAgo(90),
        nextServiceDate: daysAgo(-3),
        notes: "Awaiting replacement contactor assembly",
        createdBy: adminUser._id,
      },
      {
        name: "SkyEye Inspection Drone",
        type: "Shop Drone",
        status: "online",
        zone: "Shop Ceiling Grid",
        utilizationRate: 54,
        firmwareVersion: "1.4.9",
        connectedDevices: 2,
        lastHeartbeat: new Date(),
        lastServiceDate: daysAgo(10),
        nextServiceDate: daysAgo(20),
        createdBy: adminUser._id,
      },
    ]);
    const invoices = await Invoice.insertMany([
      {
        invoiceNumber: "AUTO-2025-0001",
        serviceLaneTicket: serviceTickets[0]._id,
        clientName: "Taylor Jennings",
        clientEmail: "taylor.jennings@example.com",
        clientPhone: "+1-470-555-2201",
        advisor: teamMembers[2]._id,
        vehicle: serviceTickets[0].vehicle,
        laborLines: [
          { servicePackage: servicePackages[0]._id, description: "Hybrid Powertrain Inspection", technician: teamMembers[1]._id, hours: 3.5, rate: 145, total: 507.5 },
        ],
        partsLines: [
          { inventoryItem: inventoryItems[3]._id, description: "HV Battery Module - 12 Cell", quantity: 1, unitPrice: 690, total: 690, taxable: true },
        ],
        shopSupplies: 22,
        hazmatFee: 12,
        discounts: 45,
        tax: 78.3,
        amount: 1184.5,
        totalAmount: 1250.8,
        balanceDue: 1250.8,
        dueDate: daysAgo(-3),
        status: "pending",
        notes: "Customer approved via SMS, pending pickup.",
        createdBy: adminUser._id,
      },
      {
        invoiceNumber: "AUTO-2025-0002",
        serviceLaneTicket: serviceTickets[1]._id,
        clientName: "Zen Fleet Services",
        clientEmail: "maintenance@zenfleet.demo",
        advisor: teamMembers[2]._id,
        vehicle: serviceTickets[1].vehicle,
        laborLines: [
          { servicePackage: servicePackages[3]._id, description: "Fleet Express Service", technician: teamMembers[5]._id, hours: 1.8, rate: 110, total: 198 },
        ],
        partsLines: [
          { inventoryItem: inventoryItems[5]._id, description: "FleetSafe Dexos Oil 5W-30", quantity: 1, unitPrice: 46, total: 46, taxable: true },
          { inventoryItem: inventoryItems[8]._id, description: "Premium Cabin Air Filter", quantity: 1, unitPrice: 11.5, total: 11.5, taxable: true },
        ],
        shopSupplies: 9,
        hazmatFee: 6,
        tax: 18.2,
        amount: 260.5,
        totalAmount: 289.7,
        balanceDue: 0,
        status: "paid",
        payments: [
          { amount: 289.7, method: "ach", reference: "ZEN-ACH-2204", receivedBy: "Evan Martinez", date: daysAgo(0) },
        ],
        createdBy: adminUser._id,
      },
      {
        invoiceNumber: "AUTO-2025-0003",
        serviceLaneTicket: serviceTickets[2]._id,
        clientName: "Vanessa Liu",
        clientEmail: "vanessa.liu@example.com",
        advisor: teamMembers[2]._id,
        vehicle: serviceTickets[2].vehicle,
        laborLines: [
          { servicePackage: servicePackages[1]._id, description: "Precision Brake Refresh", technician: teamMembers[0]._id, hours: 2.8, rate: 135, total: 378 },
        ],
        partsLines: [
          { inventoryItem: inventoryItems[0]._id, description: "Ceramic Brake Pad Kit - Front", quantity: 1, unitPrice: 68.5, total: 68.5, taxable: true },
        ],
        shopSupplies: 14,
        hazmatFee: 0,
        tax: 33.7,
        amount: 460.5,
        totalAmount: 494.2,
        balanceDue: 0,
        status: "paid",
        payments: [
          { amount: 494.2, method: "card", reference: "AUTH4312", receivedBy: "Evan Martinez", date: daysAgo(1) },
        ],
        followUpReminders: [{ description: "Brake bedding check", dueDate: daysAgo(-30) }],
        createdBy: adminUser._id,
      },
    ]);
    await InventoryTransaction.insertMany([
      {
        inventoryItem: inventoryItems[3]._id,
        itemName: inventoryItems[3].name,
        transactionType: "issue_to_repair",
        quantity: 1,
        unit: "module",
        unitCost: 690,
        totalCost: 690,
        balanceBefore: 4,
        balanceAfter: 3,
        serviceTicket: serviceTickets[0]._id,
        reason: "RO-84521 HV module replacement",
        referenceType: "ServiceTicket",
        referenceId: serviceTickets[0]._id,
        createdBy: adminUser._id,
      },
      {
        inventoryItem: inventoryItems[5]._id,
        itemName: inventoryItems[5].name,
        transactionType: "purchase",
        quantity: 24,
        unit: "case",
        unitCost: 46,
        totalCost: 1104,
        balanceBefore: 32,
        balanceAfter: 56,
        supplier: suppliers[3]._id,
        reason: "Fleet oil restock",
        referenceType: "PurchaseOrder",
        createdBy: adminUser._id,
      },
      {
        inventoryItem: inventoryItems[0]._id,
        itemName: inventoryItems[0].name,
        transactionType: "issue_to_repair",
        quantity: 1,
        unit: "set",
        unitCost: 68.5,
        totalCost: 68.5,
        balanceBefore: 22,
        balanceAfter: 21,
        serviceTicket: serviceTickets[2]._id,
        referenceType: "ServiceTicket",
        createdBy: adminUser._id,
      },
    ]);
    await Promise.all(
      inventoryItems.map(async (item, index) => {
        const minThreshold = (item as any).minThreshold ?? 0;
        item.parLevel = Math.max(1, Math.ceil(minThreshold * 1.5));
        item.restockPeriod = 'weekly';
        item.restockDays = 7;
        item.preferredSupplier = item.supplierName;
        item.vendorSku = `${item.partNumber}-SUP`;
        item.minimumOrderQuantity = (item as any).reorderQuantity ?? 1;
        item.palletQuantity = (item as any).maxCapacity ?? 0;
        item.averageDailyUsage = (item as any).averageMonthlyUsage
          ? Number(((item as any).averageMonthlyUsage / 30).toFixed(2))
          : 0;
        const wasteLogs: any[] = [];
        if (index === 0) {
          wasteLogs.push({
            date: daysAgo(4),
            quantity: 1,
            unitCost: item.costPerUnit ?? 0,
            label: 'Contamination',
            reason: 'Brake pad kit exposed to hydraulic fluid during install',
            notes: 'Removed from service bay per safety protocol',
            recordedBy: adminUser._id,
            recordedByName: adminUser.name,
          });
          wasteLogs.push({
            date: daysAgo(1),
            quantity: 1,
            unitCost: item.costPerUnit ?? 0,
            label: 'Return Damage',
            reason: 'Returned kit with bent shim plate',
            notes: 'Set aside for supplier RMA review',
            recordedBy: adminUser._id,
            recordedByName: adminUser.name,
          });
          item.wasteCategory = 'Contamination';
        } else if (index === 3) {
          wasteLogs.push({
            date: daysAgo(5),
            quantity: 0.5,
            unitCost: item.costPerUnit ?? 0,
            label: 'Damage',
            reason: 'Hose spool crushed in receiving dock incident',
            notes: 'Documented for insurance claim',
            recordedBy: adminUser._id,
            recordedByName: adminUser.name,
          });
          item.wasteCategory = 'Damage';
        } else {
          item.wasteCategory = undefined;
        }
        const wasteQuantity = wasteLogs.reduce((sum, log) => sum + (log.quantity ?? 0), 0);
        item.waste = wasteQuantity;
        item.wasteNotes = wasteLogs.length ? wasteLogs[0].notes : undefined;
        (item as any).wasteLogs = wasteLogs;
        await item.save();
      }),
    );

    await PerformanceEntry.insertMany([
      {
        restaurantGuid: 'ledgerone-autoshop',
        employeeToastGuid: teamMembers[0].toastId ?? String(teamMembers[0]._id),
        rating: 4.8,
        isFlag: false,
        salesGenerated: 1480,
        date: daysAgo(2),
        createdBy: adminUser.email,
      },
      {
        restaurantGuid: 'ledgerone-autoshop',
        employeeToastGuid: teamMembers[0].toastId ?? String(teamMembers[0]._id),
        isFlag: true,
        flagType: 'yellow',
        details: 'Documented torque re-check on EV axle conversion',
        date: daysAgo(5),
        createdBy: adminUser.email,
      },
      {
        restaurantGuid: 'ledgerone-autoshop',
        employeeToastGuid: teamMembers[1].toastId ?? String(teamMembers[1]._id),
        rating: 4.7,
        isFlag: false,
        salesGenerated: 910,
        date: daysAgo(1),
        createdBy: adminUser.email,
      },
      {
        restaurantGuid: 'ledgerone-autoshop',
        employeeToastGuid: teamMembers[1].toastId ?? String(teamMembers[1]._id),
        isFlag: true,
        flagType: 'red',
        details: 'Escalated communication issue on RO-84519',
        date: daysAgo(6),
        createdBy: adminUser.email,
      },
      {
        restaurantGuid: 'ledgerone-autoshop',
        employeeToastGuid: teamMembers[3].toastId ?? String(teamMembers[3]._id),
        rating: 4.9,
        isFlag: false,
        salesGenerated: 620,
        date: daysAgo(3),
        createdBy: adminUser.email,
      },
      {
        restaurantGuid: 'ledgerone-autoshop',
        employeeToastGuid: teamMembers[3].toastId ?? String(teamMembers[3]._id),
        isFlag: true,
        flagType: 'blue',
        details: 'Recovered rush order vendor shortage',
        date: daysAgo(4),
        createdBy: adminUser.email,
      },
    ]);

    await PurchaseOrder.insertMany([
      {
        poNumber: "PO-2025-0007",
        supplier: suppliers[3]._id,
        supplierName: suppliers[3].name,
        status: "received",
        orderDate: daysAgo(5),
        expectedDeliveryDate: daysAgo(3),
        receivedDate: daysAgo(2),
        items: [
          {
            inventoryItem: inventoryItems[5]._id,
            name: inventoryItems[5].name,
            partNumber: inventoryItems[5].partNumber,
            quantityOrdered: 24,
            quantityReceived: 24,
            unit: "case",
            unitCost: 46,
            totalCost: 1104,
          },
        ],
        notes: "Fleet express program restock",
        createdBy: adminUser._id,
      },
      {
        poNumber: "PO-2025-0008",
        supplier: suppliers[2]._id,
        supplierName: suppliers[2].name,
        status: "confirmed",
        orderDate: daysAgo(2),
        expectedDeliveryDate: daysAgo(-2),
        items: [
          {
            inventoryItem: inventoryItems[3]._id,
            name: inventoryItems[3].name,
            partNumber: inventoryItems[3].partNumber,
            quantityOrdered: 3,
            quantityReceived: 0,
            unit: "module",
            unitCost: 690,
            totalCost: 2070,
          },
        ],
        notes: "HV module replenishment",
        createdBy: adminUser._id,
      },
    ]);
    const analyticsPayload: any[] = [];
    for (let i = 12; i >= 0; i -= 1) {
      const date = daysAgo(i * 7);
      analyticsPayload.push({
        period: "weekly",
        date,
        totalRevenue: 89000 + i * 3200,
        laborRevenue: 52000 + i * 1800,
        partsRevenue: 37000 + i * 1400,
        grossProfit: 0.46,
        vehiclesServiced: 168 - i * 2,
        averageRepairOrder: 512 + i * 4,
        bayUtilization: 82 - i,
        technicianEfficiency: 91 - i * 0.3,
        diagnosticCaptureRate: 74 + i * 0.5,
        partsTurnoverDays: 27 - i * 0.4,
        comebackRate: 2.1 + i * 0.02,
        customerSatisfaction: 4.7 - i * 0.01,
        firstTimeFixRate: 93 + i * 0.2,
        openEstimates: 21 + i,
        warrantyClaims: 3 + (i % 2),
        topServiceCategories: [
          { category: "Braking", value: 18500 + i * 400, change: 4.2 },
          { category: "Diagnostics", value: 22300 - i * 290, change: 6.1 },
          { category: "EV Specialized", value: 14200 + i * 360, change: 8.4 },
        ],
        fleetVsRetailMix: [
          { category: "Retail", value: 67, change: 1.2 },
          { category: "Fleet", value: 33, change: -0.4 },
        ],
        revenueTrend: new Array(7).fill(0).map((_, idx) => ({
          label: format(daysAgo(i * 7 - (6 - idx)), "MMM d"),
          value: 11800 + idx * 620 + i * 150,
        })),
        bayPerformance: serviceBays.map((bay) => ({
          bay: bay._id,
          utilization: 68 + Math.random() * 12,
          throughput: 28 + Math.floor(Math.random() * 6),
          averageCycleTimeMinutes: 146 - Math.floor(Math.random() * 20),
        })),
        technicianLeaderboard: teamMembers.map((member) => ({
          technician: member._id,
          hoursFlagged: 38 + Math.random() * 6,
          billedHours: 36 + Math.random() * 6,
          efficiency: 90 + Math.random() * 6,
          comebacks: Math.random() > 0.8 ? 1 : 0,
          upsellRate: 22 + Math.random() * 18,
        })),
        alerts: [],
      });
    }
    await Analytics.insertMany(analyticsPayload);
    await AIInsight.insertMany([
      {
        module: "service-lane",
        title: "EV queue resilience",
        description: "EV bay idle 18% due to parts wait; pre-stage inverter coolant kit for next drop.",
        action: "Stage EV thermal kits with HV battery modules nightly.",
        urgency: "high",
        impact: "high",
        status: "open",
        createdBy: adminUser._id,
      },
      {
        module: "inventory",
        title: "Brake pad turns",
        description: "Ceramic pad kit CBP-2045F turns at 18 days vs. goal of 25 — tighten reorder window.",
        action: "Adjust reorder quantity from 12 to 16 and trigger supply review.",
        urgency: "medium",
        impact: "medium",
        status: "open",
        createdBy: adminUser._id,
      },
    ]);

    console.log("? LedgerOne Auto Shop seed completed successfully");
    process.exit(0);
  } catch (error) {
    console.error("? Seed failed", error);
    process.exit(1);
  }
}

seedDatabase();
