/**
 * Shopify CLI Helper Library
 * Executes Shopify CLI commands programmatically for app deployment
 * 
 * Requirements:
 * - SHOPIFY_CLI_PARTNERS_TOKEN: Partner API token for CLI authentication
 * - SHOPIFY_ORG_ID: Shopify Partners organization ID
 * - Node.js environment with access to child_process
 */

import { spawn, exec } from "child_process";
import { promisify } from "util";
import * as fs from "fs/promises";
import * as path from "path";
import * as os from "os";

const execAsync = promisify(exec);

export interface ShopifyAppConfig {
  name: string;
  brandKey: string;
  clientId?: string;
  applicationUrl: string;
  embedded: boolean;
  redirectUrls: string[];
  scopes: string[];
  supportUrl?: string;
  privacyUrl?: string;
  termsUrl?: string;
  extension?: {
    enabled: boolean;
    buttonLabel: string;
    minTotal: number;
    currency: string;
    palette: { primary: string; accent: string };
  };
}

export interface DeployResult {
  success: boolean;
  appId?: string;
  clientId?: string;
  appUrl?: string;
  error?: string;
  logs: string[];
}

/**
 * Check if Shopify CLI is installed
 */
export async function isShopifyCliInstalled(): Promise<boolean> {
  try {
    await execAsync("shopify version");
    return true;
  } catch {
    return false;
  }
}

/**
 * Get Shopify CLI version
 */
export async function getShopifyCliVersion(): Promise<string | null> {
  try {
    const { stdout } = await execAsync("shopify version");
    return stdout.trim();
  } catch {
    return null;
  }
}

/**
 * Generate shopify.app.toml content
 */
export function generateAppToml(config: ShopifyAppConfig): string {
  const redirectUrlsStr = config.redirectUrls.map(u => `"${u}"`).join(", ");
  const scopesStr = config.scopes.join(", ");

  return `# Shopify App Configuration
# Generated by PortalPay Plugin Studio
# Brand: ${config.brandKey}

name = "${config.name}"
client_id = "${config.clientId || ""}"
application_url = "${config.applicationUrl}"
embedded = ${config.embedded}

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "${scopesStr}"

[auth]
redirect_urls = [
  ${redirectUrlsStr}
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false

${config.supportUrl || config.privacyUrl || config.termsUrl ? `[app_proxy]
# URL configuration for app proxy
${config.supportUrl ? `# Support: ${config.supportUrl}` : ""}
${config.privacyUrl ? `# Privacy: ${config.privacyUrl}` : ""}
${config.termsUrl ? `# Terms: ${config.termsUrl}` : ""}` : ""}
`;
}

/**
 * Generate checkout UI extension configuration (shopify.extension.toml)
 */
export function generateExtensionToml(config: ShopifyAppConfig): string {
  if (!config.extension?.enabled) {
    return "";
  }

  return `# Checkout UI Extension Configuration
# Generated by PortalPay Plugin Studio

api_version = "2024-10"

[[extensions]]
name = "${config.name} - Crypto Payments"
handle = "${config.brandKey}-crypto-payment"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.checkout.payment-method-list.render-after"

[extensions.capabilities]
api_access = true
network_access = true

[extensions.settings]
[[extensions.settings.fields]]
key = "button_label"
type = "single_line_text_field"
name = "Button Label"
description = "Text displayed on the payment button"

[[extensions.settings.fields]]
key = "min_total"
type = "number_integer"
name = "Minimum Order Total"
description = "Minimum order total required to show crypto payment option"
`;
}

/**
 * Generate checkout extension source code
 */
export function generateCheckoutExtensionCode(config: ShopifyAppConfig): string {
  const ext = config.extension;
  if (!ext?.enabled) return "";

  return `import {
  reactExtension,
  Banner,
  Button,
  useApplyCartLinesChange,
  useCartLines,
  useApi,
  useSettings,
} from "@shopify/ui-extensions-react/checkout";

export default reactExtension(
  "purchase.checkout.payment-method-list.render-after",
  () => <CryptoPaymentOption />
);

function CryptoPaymentOption() {
  const { extension } = useApi();
  const settings = useSettings();
  const cartLines = useCartLines();
  
  const buttonLabel = settings.button_label ?? "${ext.buttonLabel}";
  const minTotal = settings.min_total ?? ${ext.minTotal};
  
  // Calculate cart total
  const cartTotal = cartLines.reduce((sum, line) => {
    return sum + (Number(line.cost?.totalAmount?.amount) || 0);
  }, 0);
  
  // Don't show if below minimum
  if (cartTotal < minTotal) {
    return null;
  }

  const handleCryptoPayment = () => {
    // Open crypto payment modal/redirect
    // This integrates with your backend payment processing
    const paymentUrl = \`\${extension.scriptUrl}/api/payments/crypto?session=\${extension.sessionToken}\`;
    window.open(paymentUrl, '_blank');
  };

  return (
    <Banner
      status="info"
      title="Pay with Cryptocurrency"
    >
      <Button
        kind="primary"
        appearance="monochrome"
        onPress={handleCryptoPayment}
        accessibilityLabel={buttonLabel}
      >
        {buttonLabel}
      </Button>
    </Banner>
  );
}
`;
}

/**
 * Generate package.json for the extension
 */
export function generateExtensionPackageJson(config: ShopifyAppConfig): string {
  return JSON.stringify({
    name: `${config.brandKey}-shopify-extension`,
    version: "1.0.0",
    private: true,
    scripts: {
      dev: "shopify app dev",
      build: "shopify app build",
      deploy: "shopify app deploy"
    },
    dependencies: {
      "@shopify/ui-extensions-react": "^2024.4.0",
      "react": "^18.2.0"
    },
    devDependencies: {
      "@shopify/cli": "^3.0.0",
      "typescript": "^5.0.0"
    }
  }, null, 2);
}

/**
 * Create a temporary Shopify app project directory
 */
export async function createAppProject(config: ShopifyAppConfig): Promise<string> {
  const tmpDir = path.join(os.tmpdir(), `shopify-app-${config.brandKey}-${Date.now()}`);
  
  await fs.mkdir(tmpDir, { recursive: true });
  await fs.mkdir(path.join(tmpDir, "extensions", "checkout-ui", "src"), { recursive: true });
  
  // Write app.toml
  await fs.writeFile(
    path.join(tmpDir, "shopify.app.toml"),
    generateAppToml(config)
  );
  
  // Write package.json
  await fs.writeFile(
    path.join(tmpDir, "package.json"),
    generateExtensionPackageJson(config)
  );
  
  // Write extension config if enabled
  if (config.extension?.enabled) {
    await fs.writeFile(
      path.join(tmpDir, "extensions", "checkout-ui", "shopify.extension.toml"),
      generateExtensionToml(config)
    );
    
    await fs.writeFile(
      path.join(tmpDir, "extensions", "checkout-ui", "src", "Checkout.tsx"),
      generateCheckoutExtensionCode(config)
    );
    
    // Extension package.json
    await fs.writeFile(
      path.join(tmpDir, "extensions", "checkout-ui", "package.json"),
      JSON.stringify({
        name: `${config.brandKey}-checkout-ui`,
        version: "1.0.0",
        private: true,
        dependencies: {
          "@shopify/ui-extensions-react": "^2024.4.0",
          "react": "^18.2.0"
        }
      }, null, 2)
    );
  }
  
  return tmpDir;
}

/**
 * Run Shopify CLI command
 */
export async function runShopifyCommand(
  cwd: string,
  args: string[],
  env?: Record<string, string>
): Promise<{ success: boolean; stdout: string; stderr: string }> {
  return new Promise((resolve) => {
    const logs: string[] = [];
    let stdout = "";
    let stderr = "";
    
    const proc = spawn("shopify", args, {
      cwd,
      env: {
        ...process.env,
        ...env,
        // Disable interactive mode
        CI: "true",
        SHOPIFY_FLAG_NO_PROMPT: "true",
      },
      shell: true,
    });
    
    proc.stdout.on("data", (data) => {
      const str = data.toString();
      stdout += str;
      logs.push(str);
    });
    
    proc.stderr.on("data", (data) => {
      const str = data.toString();
      stderr += str;
      logs.push(`[stderr] ${str}`);
    });
    
    proc.on("close", (code) => {
      resolve({
        success: code === 0,
        stdout,
        stderr,
      });
    });
    
    proc.on("error", (err) => {
      resolve({
        success: false,
        stdout,
        stderr: err.message,
      });
    });
  });
}

/**
 * Deploy a Shopify app using the CLI
 */
export async function deployShopifyApp(config: ShopifyAppConfig): Promise<DeployResult> {
  const logs: string[] = [];
  
  // Check for required environment variables
  const partnersToken = process.env.SHOPIFY_CLI_PARTNERS_TOKEN;
  const orgId = process.env.SHOPIFY_ORG_ID;
  
  if (!partnersToken) {
    return {
      success: false,
      error: "SHOPIFY_CLI_PARTNERS_TOKEN not configured",
      logs: ["Missing SHOPIFY_CLI_PARTNERS_TOKEN environment variable"],
    };
  }
  
  if (!orgId) {
    return {
      success: false,
      error: "SHOPIFY_ORG_ID not configured",
      logs: ["Missing SHOPIFY_ORG_ID environment variable"],
    };
  }
  
  // Check if CLI is installed
  const cliInstalled = await isShopifyCliInstalled();
  if (!cliInstalled) {
    return {
      success: false,
      error: "Shopify CLI not installed",
      logs: ["Shopify CLI not found. Install with: npm install -g @shopify/cli"],
    };
  }
  
  logs.push(`Starting deployment for ${config.name}...`);
  
  // Create project directory
  let projectDir: string;
  try {
    projectDir = await createAppProject(config);
    logs.push(`Created project directory: ${projectDir}`);
  } catch (e: any) {
    return {
      success: false,
      error: `Failed to create project: ${e.message}`,
      logs,
    };
  }
  
  const env = {
    SHOPIFY_CLI_PARTNERS_TOKEN: partnersToken,
    SHOPIFY_CLI_ORGANIZATION_ID: orgId,
  };
  
  try {
    // Step 1: Install dependencies
    logs.push("Installing dependencies...");
    const installResult = await runShopifyCommand(projectDir, ["app", "install"], env);
    if (!installResult.success) {
      // Try npm install as fallback
      try {
        await execAsync("npm install", { cwd: projectDir });
        logs.push("Dependencies installed via npm");
      } catch {
        logs.push(`Warning: dependency install had issues: ${installResult.stderr}`);
      }
    }
    
    // Step 2: Create or link app
    logs.push("Creating/linking app in Shopify Partners...");
    let appCreateResult;
    
    if (config.clientId) {
      // Link to existing app
      appCreateResult = await runShopifyCommand(
        projectDir,
        ["app", "config", "link", "--client-id", config.clientId],
        env
      );
    } else {
      // Create new app
      appCreateResult = await runShopifyCommand(
        projectDir,
        ["app", "config", "push", "--force"],
        env
      );
    }
    
    logs.push(appCreateResult.stdout || appCreateResult.stderr);
    
    // Step 3: Deploy the app
    logs.push("Deploying app...");
    const deployResult = await runShopifyCommand(
      projectDir,
      ["app", "deploy", "--force"],
      env
    );
    
    logs.push(deployResult.stdout || deployResult.stderr);
    
    if (!deployResult.success) {
      // Try alternative deployment method
      logs.push("Trying alternative deployment method...");
      const pushResult = await runShopifyCommand(
        projectDir,
        ["app", "config", "push"],
        env
      );
      logs.push(pushResult.stdout || pushResult.stderr);
      
      if (!pushResult.success) {
        return {
          success: false,
          error: "Deployment failed",
          logs,
        };
      }
    }
    
    // Try to extract app info from output
    let appId: string | undefined;
    let clientId: string | undefined;
    let appUrl: string | undefined;
    
    const outputText = deployResult.stdout + deployResult.stderr;
    
    // Parse app ID from output
    const appIdMatch = outputText.match(/app[_\s-]?id[:\s]+([a-zA-Z0-9]+)/i);
    if (appIdMatch) appId = appIdMatch[1];
    
    const clientIdMatch = outputText.match(/client[_\s-]?id[:\s]+([a-zA-Z0-9]+)/i);
    if (clientIdMatch) clientId = clientIdMatch[1];
    
    const urlMatch = outputText.match(/https:\/\/partners\.shopify\.com\/[^\s]+/);
    if (urlMatch) appUrl = urlMatch[0];
    
    // Cleanup temp directory
    try {
      await fs.rm(projectDir, { recursive: true, force: true });
    } catch {
      // Ignore cleanup errors
    }
    
    return {
      success: true,
      appId,
      clientId,
      appUrl,
      logs,
    };
  } catch (e: any) {
    logs.push(`Error: ${e.message}`);
    
    // Cleanup temp directory
    try {
      await fs.rm(projectDir, { recursive: true, force: true });
    } catch {
      // Ignore cleanup errors
    }
    
    return {
      success: false,
      error: e.message,
      logs,
    };
  }
}

/**
 * Get app info from Shopify Partners
 */
export async function getAppInfo(clientId: string): Promise<any> {
  const partnersToken = process.env.SHOPIFY_CLI_PARTNERS_TOKEN;
  const orgId = process.env.SHOPIFY_ORG_ID;
  
  if (!partnersToken || !orgId) {
    return null;
  }
  
  try {
    const tmpDir = path.join(os.tmpdir(), `shopify-info-${Date.now()}`);
    await fs.mkdir(tmpDir, { recursive: true });
    
    // Create minimal config
    await fs.writeFile(
      path.join(tmpDir, "shopify.app.toml"),
      `client_id = "${clientId}"\nname = "temp"`
    );
    
    const result = await runShopifyCommand(
      tmpDir,
      ["app", "info"],
      {
        SHOPIFY_CLI_PARTNERS_TOKEN: partnersToken,
        SHOPIFY_CLI_ORGANIZATION_ID: orgId,
      }
    );
    
    await fs.rm(tmpDir, { recursive: true, force: true });
    
    return {
      success: result.success,
      output: result.stdout,
    };
  } catch {
    return null;
  }
}
