/**
 * Comparison Landing Page Data
 * Competitor comparison pages for high-intent SEO
 */

import { ComparisonData } from './types';

export const COMPARISON_DATA: Record<string, ComparisonData> = {
  stripe: {
    slug: 'stripe',
    name: 'Stripe',
    logo: '/logos/stripe.svg',
    
    title: 'PortalPay vs Stripe | Save 70% on Processing Fees',
    metaDescription: 'Compare PortalPay vs Stripe. Pay 0.5-1% vs 2.9% + 30¢. No monthly fees. Free enterprise features. Accept crypto + cards. Switch in minutes and save $3,000+/year.',
    
    headline: 'PortalPay vs Stripe: Save 70% on Payment Processing',
    subheadline: 'Get lower fees (0.5-1% vs 2.9%), no monthly costs, and enterprise features free. Plus accept crypto payments without a bank account.',
    
    pricing: {
      processingFee: 0.029,
      flatFee: 0.30,
      monthlyFee: 0,
      annualSoftwareCost: 0,
    },
    
    features: [
      {
        feature: 'Processing Fee',
        portalpay: '0.5-1%',
        competitor: '2.9% + 30¢',
        advantage: true,
      },
      {
        feature: 'Monthly Fee',
        portalpay: '$0',
        competitor: '$0 (basic) - $100+ (advanced)',
        advantage: true,
      },
      {
        feature: 'Settlement Time',
        portalpay: 'Instant (seconds)',
        competitor: '2 business days',
        advantage: true,
      },
      {
        feature: 'Chargebacks',
        portalpay: 'Zero (crypto finality)',
        competitor: 'Yes (lose 1-2%)',
        advantage: true,
      },
      {
        feature: 'Accept Crypto',
        portalpay: true,
        competitor: 'No (need separate solution)',
        advantage: true,
      },
      {
        feature: 'Accept Cards',
        portalpay: true,
        competitor: true,
        advantage: false,
      },
      {
        feature: 'Bank Account Required',
        portalpay: 'No (crypto wallet)',
        competitor: 'Yes (mandatory)',
        advantage: true,
      },
      {
        feature: 'International Payments',
        portalpay: 'No FX fees',
        competitor: '1-3% FX fees',
        advantage: true,
      },
      {
        feature: 'POS System',
        portalpay: 'Free (included)',
        competitor: 'Extra cost or third-party',
        advantage: true,
      },
      {
        feature: 'Analytics Dashboard',
        portalpay: 'Free (included)',
        competitor: 'Extra $100/mo',
        advantage: true,
      },
      {
        feature: 'White-Label Portal',
        portalpay: 'Free (included)',
        competitor: 'Not available',
        advantage: true,
      },
      {
        feature: 'Revenue Splits',
        portalpay: 'Free (on-chain)',
        competitor: 'Extra cost',
        advantage: true,
      },
      {
        feature: 'Multi-Currency',
        portalpay: '5+ cryptos',
        competitor: '135+ fiat',
        advantage: false,
      },
      {
        feature: 'Subscription Billing',
        portalpay: true,
        competitor: true,
        advantage: false,
      },
      {
        feature: 'Developer API',
        portalpay: true,
        competitor: true,
        advantage: false,
      },
    ],
    
    migrationSteps: [
      'Export your transaction history from Stripe dashboard',
      'Connect your crypto wallet to PortalPay (or create new one)',
      'Upload logo, set colors, configure branding',
      'Import product catalog or rebuild menu/inventory',
      'Test with a small transaction',
      'Update payment links on your website/app',
      'Notify customers (optional - they can still use cards)',
      'Monitor transition in PortalPay dashboard',
    ],
    
    useCases: [
      {
        scenario: 'Small E-commerce Store',
        competitorCost: 3840,
        portalpayCost: 900,
        savings: 2940,
      },
      {
        scenario: 'Restaurant ($15k/month)',
        competitorCost: 5988,
        portalpayCost: 1350,
        savings: 4638,
      },
      {
        scenario: 'SaaS Business ($50k/month)',
        competitorCost: 17640,
        portalpayCost: 4500,
        savings: 13140,
      },
      {
        scenario: 'Retail Store ($10k/month)',
        competitorCost: 3840,
        portalpayCost: 900,
        savings: 2940,
      },
    ],
  },

  square: {
    slug: 'square',
    name: 'Square',
    logo: '/logos/square.svg',
    
    title: 'PortalPay vs Square | 70% Lower Fees + Free POS',
    metaDescription: 'Compare PortalPay vs Square. Pay 0.5-1% vs 2.6% + 10¢. Free POS vs $60-300/mo. Save $2,500+/year. Switch in minutes and keep your customers.',
    
    headline: 'PortalPay vs Square: Pay Less, Get More',
    subheadline: 'Lower processing fees, free POS software, instant settlement, and accept crypto payments. Perfect Square alternative for restaurants, retail, and services.',
    
    pricing: {
      processingFee: 0.026,
      flatFee: 0.10,
      monthlyFee: 60,
      annualSoftwareCost: 720,
    },
    
    features: [
      {
        feature: 'Processing Fee',
        portalpay: '0.5-1%',
        competitor: '2.6% + 10¢',
        advantage: true,
      },
      {
        feature: 'Monthly POS Fee',
        portalpay: '$0',
        competitor: '$60-300',
        advantage: true,
      },
      {
        feature: 'Annual Software Cost',
        portalpay: '$0',
        competitor: '$720-3,600',
        advantage: true,
      },
      {
        feature: 'Settlement Speed',
        portalpay: 'Instant',
        competitor: '1-2 business days',
        advantage: true,
      },
      {
        feature: 'Chargebacks',
        portalpay: 'Zero',
        competitor: 'Yes (1-2% loss)',
        advantage: true,
      },
      {
        feature: 'Accept Crypto',
        portalpay: true,
        competitor: false,
        advantage: true,
      },
      {
        feature: 'Accept Cards',
        portalpay: true,
        competitor: true,
        advantage: false,
      },
      {
        feature: 'Bank Account Required',
        portalpay: false,
        competitor: true,
        advantage: true,
      },
      {
        feature: 'Restaurant POS',
        portalpay: 'Free',
        competitor: '$60/mo',
        advantage: true,
      },
      {
        feature: 'Retail POS',
        portalpay: 'Free',
        competitor: '$60/mo',
        advantage: true,
      },
      {
        feature: 'Inventory Management',
        portalpay: 'Free',
        competitor: 'Included',
        advantage: false,
      },
      {
        feature: 'Customer Directory',
        portalpay: 'Free',
        competitor: 'Included',
        advantage: false,
      },
      {
        feature: 'Hardware',
        portalpay: 'Use any device',
        competitor: 'Buy Square hardware',
        advantage: true,
      },
      {
        feature: 'Multi-Location',
        portalpay: 'Free',
        competitor: '$60+/location',
        advantage: true,
      },
      {
        feature: 'Payroll',
        portalpay: 'Coming soon',
        competitor: '$35/mo + $6/person',
        advantage: false,
      },
    ],
    
    migrationSteps: [
      'Export customer and product data from Square',
      'Set up PortalPay account with crypto wallet',
      'Import your product catalog',
      'Test transactions with small amounts',
      'Train staff on new QR code system (5 minutes)',
      'Display QR codes at checkout or on receipts',
      'Run both systems in parallel for 1 week (optional)',
      'Fully switch to PortalPay',
    ],
    
    useCases: [
      {
        scenario: 'Coffee Shop ($7k/month)',
        competitorCost: 2904,
        portalpayCost: 630,
        savings: 2274,
      },
      {
        scenario: 'Restaurant ($12k/month)',
        competitorCost: 4272,
        portalpayCost: 1080,
        savings: 3192,
      },
      {
        scenario: 'Retail Boutique ($8k/month)',
        competitorCost: 3288,
        portalpayCost: 720,
        savings: 2568,
      },
      {
        scenario: 'Service Business ($5k/month)',
        competitorCost: 2220,
        portalpayCost: 450,
        savings: 1770,
      },
    ],
  },

  paypal: {
    slug: 'paypal',
    name: 'PayPal',
    logo: '/logos/paypal.svg',
    
    title: 'PortalPay vs PayPal | Lower Fees + Better Features',
    metaDescription: 'Compare PortalPay vs PayPal. Pay 0.5-1% vs 2.9% + 30¢. Instant settlement vs 1-3 days. Accept crypto + cards. No account holds. Save $3,000+/year.',
    
    headline: 'PortalPay vs PayPal: Modern Payment Processing',
    subheadline: 'Pay less, settle faster, and avoid PayPal account holds. Accept both crypto and traditional payments with enterprise features included free.',
    
    pricing: {
      processingFee: 0.029,
      flatFee: 0.30,
      monthlyFee: 0,
      annualSoftwareCost: 0,
    },
    
    features: [
      {
        feature: 'Processing Fee',
        portalpay: '0.5-1%',
        competitor: '2.9% + 30¢',
        advantage: true,
      },
      {
        feature: 'Settlement Time',
        portalpay: 'Instant',
        competitor: '1-3 business days',
        advantage: true,
      },
      {
        feature: 'Account Holds',
        portalpay: 'Never',
        competitor: 'Common (180 days)',
        advantage: true,
      },
      {
        feature: 'Chargebacks',
        portalpay: 'Zero (crypto)',
        competitor: 'Yes (lose disputes)',
        advantage: true,
      },
      {
        feature: 'Accept Crypto',
        portalpay: true,
        competitor: 'Limited',
        advantage: true,
      },
      {
        feature: 'Accept Cards',
        portalpay: true,
        competitor: true,
        advantage: false,
      },
      {
        feature: 'Bank Account Required',
        portalpay: false,
        competitor: true,
        advantage: true,
      },
      {
        feature: 'Invoicing',
        portalpay: true,
        competitor: true,
        advantage: false,
      },
      {
        feature: 'Subscription Billing',
        portalpay: true,
        competitor: true,
        advantage: false,
      },
      {
        feature: 'International Fees',
        portalpay: 'None',
        competitor: '1.5% + fixed fee',
        advantage: true,
      },
      {
        feature: 'Currency Conversion',
        portalpay: 'No fees',
        competitor: '3-4% markup',
        advantage: true,
      },
      {
        feature: 'POS System',
        portalpay: 'Free included',
        competitor: 'Extra cost',
        advantage: true,
      },
      {
        feature: 'Customer Support',
        portalpay: 'Direct support',
        competitor: 'Limited (automated)',
        advantage: true,
      },
    ],
    
    migrationSteps: [
      'Download transaction history from PayPal',
      'Create PortalPay account with crypto wallet',
      'Set up payment links or QR codes',
      'Test with a small payment',
      'Update website payment buttons',
      'Notify customers of new payment option',
      'Monitor both systems during transition',
      'Close PayPal once comfortable',
    ],
    
    useCases: [
      {
        scenario: 'Freelance Designer ($5k/month)',
        competitorCost: 1836,
        portalpayCost: 450,
        savings: 1386,
      },
      {
        scenario: 'Online Store ($20k/month)',
        competitorCost: 7080,
        portalpayCost: 1800,
        savings: 5280,
      },
      {
        scenario: 'Consulting Business ($10k/month)',
        competitorCost: 3540,
        portalpayCost: 900,
        savings: 2640,
      },
      {
        scenario: 'Digital Products ($15k/month)',
        competitorCost: 5310,
        portalpayCost: 1350,
        savings: 3960,
      },
    ],
  },

  toast: {
    slug: 'toast',
    name: 'Toast',
    logo: '/logos/toast.svg',
    
    title: 'PortalPay vs Toast | Save $3,000+/Year on Restaurant POS',
    metaDescription: 'Compare PortalPay vs Toast for restaurants. Pay 0.5-1% vs 2.49% + 15¢. Free POS vs $165/mo. Free KDS. Save $3,000-5,000 annually. Switch today.',
    
    headline: 'PortalPay vs Toast: Restaurant Payment Processing',
    subheadline: 'Pay 70% less in fees, get free kitchen display system, and accept crypto payments. Purpose-built for restaurants without the Toast price tag.',
    
    pricing: {
      processingFee: 0.0249,
      flatFee: 0.15,
      monthlyFee: 165,
      annualSoftwareCost: 1980,
    },
    
    features: [
      {
        feature: 'Processing Fee',
        portalpay: '0.5-1%',
        competitor: '2.49% + 15¢',
        advantage: true,
      },
      {
        feature: 'Monthly Software Fee',
        portalpay: '$0',
        competitor: '$165/mo per terminal',
        advantage: true,
      },
      {
        feature: 'Annual Software Cost',
        portalpay: '$0',
        competitor: '$1,980+',
        advantage: true,
      },
      {
        feature: 'Kitchen Display',
        portalpay: 'Free',
        competitor: 'Included',
        advantage: false,
      },
      {
        feature: 'Table Management',
        portalpay: 'Free',
        competitor: 'Included',
        advantage: false,
      },
      {
        feature: 'Menu Management',
        portalpay: 'Free',
        competitor: 'Included',
        advantage: false,
      },
      {
        feature: 'Online Ordering',
        portalpay: 'Free',
        competitor: 'Extra fee',
        advantage: true,
      },
      {
        feature: 'Gift Cards',
        portalpay: 'Free',
        competitor: '$50/mo',
        advantage: true,
      },
      {
        feature: 'Loyalty Program',
        portalpay: 'Free',
        competitor: '$50/mo',
        advantage: true,
      },
      {
        feature: 'Settlement Speed',
        portalpay: 'Instant',
        competitor: '2-3 days',
        advantage: true,
      },
      {
        feature: 'Hardware Required',
        portalpay: 'Any device',
        competitor: 'Toast hardware ($799+)',
        advantage: true,
      },
      {
        feature: 'Contract',
        portalpay: 'None',
        competitor: 'Often required',
        advantage: true,
      },
      {
        feature: 'Setup Fee',
        portalpay: '$0',
        competitor: '$0-500',
        advantage: true,
      },
    ],
    
    migrationSteps: [
      'Export menu from Toast system',
      'Set up PortalPay with crypto wallet',
      'Import menu with modifiers and pricing',
      'Set up kitchen display on tablet',
      'Configure table layout',
      'Train staff on QR code system',
      'Run parallel for one week',
      'Complete switch to PortalPay',
    ],
    
    useCases: [
      {
        scenario: 'Small Cafe ($7k/month)',
        competitorCost: 4254,
        portalpayCost: 630,
        savings: 3624,
      },
      {
        scenario: 'Casual Dining ($15k/month)',
        competitorCost: 6708,
        portalpayCost: 1350,
        savings: 5358,
      },
      {
        scenario: 'Fast Casual ($12k/month)',
        competitorCost: 5868,
        portalpayCost: 1080,
        savings: 4788,
      },
      {
        scenario: 'Fine Dining ($25k/month)',
        competitorCost: 10230,
        portalpayCost: 2250,
        savings: 7980,
      },
    ],
  },

  'coinbase-commerce': {
    slug: 'coinbase-commerce',
    name: 'Coinbase Commerce',
    logo: '/logos/coinbase.svg',
    
    title: 'PortalPay vs Coinbase Commerce | Better Features + Lower Fees',
    metaDescription: 'Compare PortalPay vs Coinbase Commerce. Pay 0.5-1% vs 1%. Free POS, PMS, analytics included. Accept cards too. Better for businesses. Save money and get more features.',
    
    headline: 'PortalPay vs Coinbase Commerce: Complete Solution',
    subheadline: 'Lower fees, plus accept traditional payments. Free POS/PMS systems. Built for real businesses, not just crypto enthusiasts.',
    
    pricing: {
      processingFee: 0.01,
      flatFee: 0,
      monthlyFee: 0,
      annualSoftwareCost: 0,
    },
    
    features: [
      {
        feature: 'Processing Fee',
        portalpay: '0.5-1%',
        competitor: '1%',
        advantage: true,
      },
      {
        feature: 'Accept Crypto',
        portalpay: true,
        competitor: true,
        advantage: false,
      },
      {
        feature: 'Accept Cards/Apple Pay',
        portalpay: 'Yes (via onramp)',
        competitor: 'No',
        advantage: true,
      },
      {
        feature: 'Customer Needs Crypto',
        portalpay: 'No',
        competitor: 'Yes',
        advantage: true,
      },
      {
        feature: 'POS System',
        portalpay: 'Free included',
        competitor: 'Not available',
        advantage: true,
      },
      {
        feature: 'Restaurant Features',
        portalpay: 'Full POS + KDS',
        competitor: 'Payment only',
        advantage: true,
      },
      {
        feature: 'Hotel PMS',
        portalpay: 'Free included',
        competitor: 'Not available',
        advantage: true,
      },
      {
        feature: 'Retail Inventory',
        portalpay: 'Free included',
        competitor: 'Not available',
        advantage: true,
      },
      {
        feature: 'Analytics Dashboard',
        portalpay: 'Free included',
        competitor: 'Basic only',
        advantage: true,
      },
      {
        feature: 'White-Label',
        portalpay: 'Full branding',
        competitor: 'Limited',
        advantage: true,
      },
      {
        feature: 'Settlement',
        portalpay: 'Instant',
        competitor: 'Instant',
        advantage: false,
      },
      {
        feature: 'Supported Tokens',
        portalpay: '5+ on Base',
        competitor: '100+ multi-chain',
        advantage: false,
      },
      {
        feature: 'Customer Support',
        portalpay: 'Direct',
        competitor: 'Email only',
        advantage: true,
      },
    ],
    
    migrationSteps: [
      'Keep Coinbase Commerce if desired',
      'Add PortalPay for expanded features',
      'Enable card payments via onramp',
      'Use free POS/PMS systems',
      'Serve both crypto natives and traditional customers',
      'Compare which works better for your use case',
    ],
    
    useCases: [
      {
        scenario: 'Online Store ($10k crypto/month)',
        competitorCost: 1200,
        portalpayCost: 750,
        savings: 450,
      },
      {
        scenario: 'Restaurant ($15k mixed/month)',
        competitorCost: 1800,
        portalpayCost: 1125,
        savings: 675,
      },
      {
        scenario: 'Service Business ($8k/month)',
        competitorCost: 960,
        portalpayCost: 600,
        savings: 360,
      },
      {
        scenario: 'Retail Store ($12k/month)',
        competitorCost: 1440,
        portalpayCost: 900,
        savings: 540,
      },
    ],
  },

  // New global and regional competitors
  adyen: {
    slug: 'adyen',
    name: 'Adyen',
    logo: '/logos/adyen.svg',
    title: 'PortalPay vs Adyen | Lower Fees, No Monthly Costs',
    metaDescription: 'Compare PortalPay vs Adyen. Pay 0.5-1% vs ~2.9% + fixed fee. Instant settlement. Accept crypto + cards. No hardware lock-in.',
    headline: 'PortalPay vs Adyen: Modern Payments Without the Overhead',
    subheadline: 'Cut fees, settle instantly, and get free POS/PMS features. Accept crypto without bank hurdles.',
    pricing: {
      processingFee: 0.029,
      flatFee: 0.12,
      monthlyFee: 0,
      annualSoftwareCost: 0,
    },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2.9% + 12¢', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-2 days', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
      { feature: 'POS/PMS', portalpay: 'Free included', competitor: 'Enterprise add-ons', advantage: true },
      { feature: 'Hardware', portalpay: 'Any device', competitor: 'Preferred hardware', advantage: true },
      { feature: 'Bank Requirement', portalpay: 'No', competitor: 'Yes', advantage: true },
    ],
    useCases: [
      { scenario: 'Global E-commerce ($30k/mo)', competitorCost: 10440, portalpayCost: 2250, savings: 8190 },
      { scenario: 'Subscription SaaS ($20k/mo)', competitorCost: 6960, portalpayCost: 1500, savings: 5460 },
      { scenario: 'Retail Chain ($25k/mo)', competitorCost: 8700, portalpayCost: 1875, savings: 6825 },
    ],
  },

  worldpay: {
    slug: 'worldpay',
    name: 'Worldpay',
    logo: '/logos/worldpay.svg',
    title: 'PortalPay vs Worldpay | Lower Fees + Instant Settlement',
    metaDescription: 'Compare PortalPay vs Worldpay. Pay 0.5-1% vs ~2.75% + 20¢. Transparent pricing, no contracts, and crypto support.',
    headline: 'PortalPay vs Worldpay: Transparent, Fast, and Affordable',
    subheadline: 'Stop overpaying. Get instant settlement and modern features free.',
    pricing: {
      processingFee: 0.0275,
      flatFee: 0.20,
      monthlyFee: 25,
      annualSoftwareCost: 300,
    },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2.75% + 20¢', advantage: true },
      { feature: 'Monthly Fee', portalpay: '$0', competitor: '$25+', advantage: true },
      { feature: 'Contracts', portalpay: 'None', competitor: 'Common', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-3 days', advantage: true },
      { feature: 'Chargebacks', portalpay: 'Zero', competitor: 'Yes', advantage: true },
      { feature: 'Bank Requirement', portalpay: 'No', competitor: 'Yes', advantage: true },
    ],
    useCases: [
      { scenario: 'Restaurant ($12k/mo)', competitorCost: 4272, portalpayCost: 1080, savings: 3192 },
      { scenario: 'Retail ($10k/mo)', competitorCost: 3420, portalpayCost: 900, savings: 2520 },
      { scenario: 'Service ($8k/mo)', competitorCost: 2736, portalpayCost: 720, savings: 2016 },
    ],
  },

  razorpay: {
    slug: 'razorpay',
    name: 'Razorpay',
    logo: '/logos/razorpay.svg',
    title: 'PortalPay vs Razorpay | Global Payments Without FX Fees',
    metaDescription: 'Compare PortalPay vs Razorpay. Pay 0.5-1% vs ~2% local fees. No FX markups. Instant settlement. Crypto + cards.',
    headline: 'PortalPay vs Razorpay: Cross-Border Friendly and Lower Fees',
    subheadline: 'Serve international customers without conversion costs or delays.',
    pricing: {
      processingFee: 0.02,
      flatFee: 0,
      monthlyFee: 0,
      annualSoftwareCost: 0,
    },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2% (local)', advantage: true },
      { feature: 'FX Fees', portalpay: 'None', competitor: '1-3% markup', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-3 days', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
      { feature: 'Bank Requirement', portalpay: 'No', competitor: 'Yes', advantage: true },
    ],
    useCases: [
      { scenario: 'Online Services ($6k/mo)', competitorCost: 1440, portalpayCost: 540, savings: 900 },
      { scenario: 'EdTech ($10k/mo)', competitorCost: 2400, portalpayCost: 900, savings: 1500 },
      { scenario: 'SMB SaaS ($15k/mo)', competitorCost: 3600, portalpayCost: 1350, savings: 2250 },
    ],
  },

  paystack: {
    slug: 'paystack',
    name: 'Paystack',
    logo: '/logos/paystack.svg',
    title: 'PortalPay vs Paystack | Lower Fees + Cross-Border Friendly',
    metaDescription: 'Compare PortalPay vs Paystack. Pay 0.5-1% vs ~1.5% + fixed fee. Instant settlement, crypto + cards, no bank needed.',
    headline: 'PortalPay vs Paystack: Modern Payments for African Businesses',
    subheadline: 'Lower fees, international-friendly, and crypto support out of the box.',
    pricing: {
      processingFee: 0.015,
      flatFee: 0.15,
      monthlyFee: 0,
      annualSoftwareCost: 0,
    },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '1.5% + ₦100', advantage: true },
      { feature: 'International Fees', portalpay: 'None', competitor: 'Up to 3.9% extra', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: 'T+1', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
      { feature: 'POS/PMS', portalpay: 'Free included', competitor: 'Payment only', advantage: true },
    ],
    useCases: [
      { scenario: 'Retail ($8k/mo)', competitorCost: 1920, portalpayCost: 720, savings: 1200 },
      { scenario: 'Restaurant ($10k/mo)', competitorCost: 2400, portalpayCost: 900, savings: 1500 },
      { scenario: 'Freelance ($5k/mo)', competitorCost: 1200, portalpayCost: 450, savings: 750 },
    ],
  },

  flutterwave: {
    slug: 'flutterwave',
    name: 'Flutterwave',
    logo: '/logos/flutterwave.svg',
    title: 'PortalPay vs Flutterwave | Lower Fees + Crypto Support',
    metaDescription: 'Compare PortalPay vs Flutterwave. Pay 0.5-1% vs ~2.9% local. No monthly fees. Instant settlement.',
    headline: 'PortalPay vs Flutterwave: Pay Less, Settle Faster',
    subheadline: 'Avoid high local fees and get crypto support with instant settlement.',
    pricing: {
      processingFee: 0.029,
      flatFee: 0,
      monthlyFee: 0,
      annualSoftwareCost: 0,
    },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2.9%', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-2 days', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
      { feature: 'Bank Requirement', portalpay: 'No', competitor: 'Yes', advantage: true },
      { feature: 'International Fees', portalpay: 'None', competitor: '1-3% FX', advantage: true },
    ],
    useCases: [
      { scenario: 'DTC Brand ($12k/mo)', competitorCost: 4176, portalpayCost: 1080, savings: 3096 },
      { scenario: 'Events ($7k/mo)', competitorCost: 2436, portalpayCost: 630, savings: 1806 },
      { scenario: 'SaaS ($9k/mo)', competitorCost: 3132, portalpayCost: 810, savings: 2322 },
    ],
  },

  'mercado-pago': {
    slug: 'mercado-pago',
    name: 'Mercado Pago',
    logo: '/logos/mercado-pago.svg',
    title: 'PortalPay vs Mercado Pago | Lower Fees + No FX Markups',
    metaDescription: 'Compare PortalPay vs Mercado Pago. Pay 0.5-1% vs ~3.49%. Instant settlement, crypto + cards, transparent pricing.',
    headline: 'PortalPay vs Mercado Pago: Simple, Transparent, and Fast',
    subheadline: 'Get paid instantly and save on fees, with cross-border friendly payments.',
    pricing: {
      processingFee: 0.0349,
      flatFee: 0.10,
      monthlyFee: 0,
      annualSoftwareCost: 0,
    },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '3.49% + fixed', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-3 days', advantage: true },
      { feature: 'FX Fees', portalpay: 'None', competitor: 'Markup applies', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
      { feature: 'POS/PMS', portalpay: 'Free included', competitor: 'Payment only', advantage: true },
    ],
    useCases: [
      { scenario: 'Retail ($10k/mo)', competitorCost: 4200, portalpayCost: 900, savings: 3300 },
      { scenario: 'Restaurant ($15k/mo)', competitorCost: 6300, portalpayCost: 1350, savings: 4950 },
      { scenario: 'Marketplace ($20k/mo)', competitorCost: 8400, portalpayCost: 1800, savings: 6600 },
    ],
  },

  mpesa: {
    slug: 'mpesa',
    name: 'M‑Pesa',
    logo: '/logos/mpesa.svg',
    title: 'PortalPay vs M‑Pesa | Lower Fees + Cross-Border',
    metaDescription: 'Compare PortalPay vs M‑Pesa. Pay 0.5-1% vs mobile money fees. Accept crypto + cards, settle instantly, export audit-ready reports.',
    headline: 'PortalPay vs M‑Pesa: Global-Friendly and Transparent',
    subheadline: 'Keep mobile money if you like—add PortalPay for lower fees, instant settlement, and cross-border reach.',
    pricing: {
      processingFee: 0.015,
      flatFee: 0.10,
      monthlyFee: 0,
      annualSoftwareCost: 0,
    },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '~1.5% + fixed', advantage: true },
      { feature: 'Cross-Border', portalpay: 'Yes', competitor: 'Limited', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: 'Instant/Next-day', advantage: false },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
      { feature: 'POS/PMS', portalpay: 'Free included', competitor: 'Payment only', advantage: true },
    ],
    migrationSteps: [
      'Keep M‑Pesa for local flows',
      'Add PortalPay for lower fees and cross-border reach',
      'Enable card payments via onramp',
      'Use free POS/PMS features',
    ],
    useCases: [
      { scenario: 'Kiosk ($6k/mo)', competitorCost: 1440, portalpayCost: 540, savings: 900 },
      { scenario: 'Transport ($9k/mo)', competitorCost: 2160, portalpayCost: 810, savings: 1350 },
      { scenario: 'Retail ($12k/mo)', competitorCost: 2880, portalpayCost: 1080, savings: 1800 },
    ],
  },

  'checkout-com': {
    slug: 'checkout-com',
    name: 'Checkout.com',
    logo: '/logos/checkout-com.svg',
    title: 'PortalPay vs Checkout.com | Lower Fees + Instant Settlement',
    metaDescription: 'Compare PortalPay vs Checkout.com. Pay 0.5-1% vs 2.9% + 20¢. No monthly fees. Crypto + cards. Free enterprise features.',
    headline: 'PortalPay vs Checkout.com: Save Money and Time',
    subheadline: 'Fast settlement, lower fees, and full-stack features at no extra cost.',
    pricing: {
      processingFee: 0.029,
      flatFee: 0.20,
      monthlyFee: 0,
      annualSoftwareCost: 0,
    },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2.9% + 20¢', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-2 days', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: 'Limited', advantage: true },
      { feature: 'Bank Requirement', portalpay: 'No', competitor: 'Yes', advantage: true },
      { feature: 'POS/PMS', portalpay: 'Free included', competitor: 'Payment only', advantage: true },
    ],
    useCases: [
      { scenario: 'Marketplace ($25k/mo)', competitorCost: 9300, portalpayCost: 1875, savings: 7425 },
      { scenario: 'Subscription ($18k/mo)', competitorCost: 6696, portalpayCost: 1350, savings: 5346 },
      { scenario: 'Retail ($12k/mo)', competitorCost: 4464, portalpayCost: 1080, savings: 3384 },
    ],
  },

  bitpay: {
    slug: 'bitpay',
    name: 'BitPay',
    logo: '/logos/bitpay.svg',
    title: 'PortalPay vs BitPay | More Features + Lower Effective Cost',
    metaDescription: 'Compare PortalPay vs BitPay. Pay 0.5-1% vs 1%. Accept cards via onramp. Free POS/PMS. Instant settlement.',
    headline: 'PortalPay vs BitPay: Business-Ready Crypto Payments',
    subheadline: 'Get crypto plus cards, POS/PMS, and instant settlement—all at lower effective cost.',
    pricing: {
      processingFee: 0.01,
      flatFee: 0,
      monthlyFee: 0,
      annualSoftwareCost: 0,
    },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '1%', advantage: true },
      { feature: 'Accept Cards', portalpay: 'Yes (onramp)', competitor: 'No', advantage: true },
      { feature: 'POS/PMS', portalpay: 'Free included', competitor: 'Not included', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: 'Instant', advantage: false },
      { feature: 'White-Label', portalpay: 'Full branding', competitor: 'Limited', advantage: true },
    ],
    migrationSteps: [
      'Keep BitPay if desired',
      'Add PortalPay for card onramp and POS/PMS',
      'Compare effective costs and features',
    ],
    useCases: [
      { scenario: 'Crypto-Native Store ($10k/mo)', competitorCost: 1200, portalpayCost: 750, savings: 450 },
      { scenario: 'Events ($7k/mo)', competitorCost: 840, portalpayCost: 525, savings: 315 },
      { scenario: 'Digital Goods ($5k/mo)', competitorCost: 600, portalpayCost: 375, savings: 225 },
    ],
  },
  flexa: {
    slug: 'flexa',
    name: 'Flexa',
    logo: '/logos/flexa.svg',
    title: 'PortalPay vs Flexa | Instant Settlement Without Token Collateral',
    metaDescription: 'Compare PortalPay vs Flexa. PortalPay settles instantly without collateral tokens. Flexa relies on the AMP token (widely criticized as a scam collateral token) and does not provide instant settlement. Lower fees, free POS/PMS, crypto + cards.',
    headline: 'PortalPay vs Flexa: No Token Collateral, Real Instant Settlement',
    subheadline: 'Avoid token-collateral delays. Settle in seconds on-chain with lower fees and full-stack features.',
    pricing: {
      processingFee: 0.01,
      flatFee: 0,
      monthlyFee: 0,
      annualSoftwareCost: 0
    },
    features: [
      { feature: 'Settlement', portalpay: 'Instant (seconds)', competitor: 'Not instant (token-collateral delays)', advantage: true },
      { feature: 'Collateral Token', portalpay: 'None required', competitor: 'Requires AMP \'scam\' token collateral', advantage: true },
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '≈1%', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: true, advantage: false },
      { feature: 'Accept Cards/Apple Pay', portalpay: 'Yes (onramp)', competitor: 'Limited', advantage: true },
      { feature: 'POS/PMS', portalpay: 'Free included', competitor: 'Payment only', advantage: true },
      { feature: 'Bank Requirement', portalpay: 'No', competitor: 'Varies', advantage: true }
    ],
    migrationSteps: [
      'Export transaction records from Flexa',
      'Create PortalPay account and connect wallet',
      'Enable card onramp for traditional customers',
      'Import catalog or configure presets',
      'Run a pilot alongside Flexa for one week',
      'Switch fully to instant settlement with PortalPay'
    ],
    useCases: [
      { scenario: 'Retail ($12k/mo)', competitorCost: 1200, portalpayCost: 900, savings: 300 },
      { scenario: 'Events ($7k/mo)', competitorCost: 700, portalpayCost: 525, savings: 175 },
      { scenario: 'Cafe ($8k/mo)', competitorCost: 800, portalpayCost: 600, savings: 200 }
    ]
  },
  'clover-fiserv': {
    slug: 'clover-fiserv',
    name: 'Clover (Fiserv)',
    logo: '/logos/clover.png',
    title: 'PortalPay vs Clover (Fiserv) | Lower Fees + No Hardware Lock‑In',
    metaDescription: 'Compare PortalPay vs Clover by Fiserv. Pay 0.5-1% vs ~2.3% + 10¢. No monthly fees vs $15-70+. Free POS/KDS. Instant settlement. Accept crypto + cards.',
    headline: 'PortalPay vs Clover: Cut Costs, Keep Flexibility',
    subheadline: 'Lower fees, instant settlement, and free POS/KDS on any hardware—no lock‑in.',
    pricing: {
      processingFee: 0.023,
      flatFee: 0.10,
      monthlyFee: 30,
      annualSoftwareCost: 360,
    },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2.3% + 10¢', advantage: true },
      { feature: 'Monthly Fee', portalpay: '$0', competitor: '$15-70+', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-2 days', advantage: true },
      { feature: 'Hardware', portalpay: 'Any device', competitor: 'Clover hardware required', advantage: true },
      { feature: 'Chargebacks', portalpay: 'Zero (crypto)', competitor: 'Yes', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
      { feature: 'Accept Cards', portalpay: true, competitor: true, advantage: false },
      { feature: 'Bank Account Required', portalpay: 'No', competitor: 'Yes', advantage: true },
    ],
    migrationSteps: [
      'Export menu/products from Clover',
      'Create PortalPay account and connect wallet',
      'Import catalog and configure POS/KDS',
      'Run both systems in parallel for a week (optional)',
      'Switch fully when ready',
    ],
    useCases: [
      { scenario: 'Cafe ($8k/mo)', competitorCost: 2640, portalpayCost: 720, savings: 1920 },
      { scenario: 'Retail ($12k/mo)', competitorCost: 3960, portalpayCost: 1080, savings: 2880 },
      { scenario: 'Restaurant ($18k/mo)', competitorCost: 5940, portalpayCost: 1620, savings: 4320 },
    ],
  },

  'global-payments': {
    slug: 'global-payments',
    name: 'Global Payments (TSYS)',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs Global Payments/TSYS | Transparent, Faster, Cheaper',
    metaDescription: 'Compare PortalPay vs Global Payments/TSYS. Pay 0.5-1% vs ~2.75% + 20¢. No contracts. Instant settlement. Crypto + cards.',
    headline: 'PortalPay vs Global Payments: Modern Payments Without Gotchas',
    subheadline: 'Lower fees, instant settlement, no contracts, and crypto support.',
    pricing: {
      processingFee: 0.0275,
      flatFee: 0.20,
      monthlyFee: 15,
      annualSoftwareCost: 180,
    },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2.75% + 20¢', advantage: true },
      { feature: 'Monthly Fee', portalpay: '$0', competitor: '$15+', advantage: true },
      { feature: 'Contracts', portalpay: 'None', competitor: 'Common', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-3 days', advantage: true },
      { feature: 'Chargebacks', portalpay: 'Zero', competitor: 'Yes', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
    ],
    useCases: [
      { scenario: 'Retail ($10k/mo)', competitorCost: 3420, portalpayCost: 900, savings: 2520 },
      { scenario: 'Restaurant ($15k/mo)', competitorCost: 5130, portalpayCost: 1350, savings: 3780 },
      { scenario: 'Service ($8k/mo)', competitorCost: 2736, portalpayCost: 720, savings: 2016 },
    ],
  },

  elavon: {
    slug: 'elavon',
    name: 'Elavon',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs Elavon | Lower Fees + Instant Settlement',
    metaDescription: 'Compare PortalPay vs Elavon. Pay 0.5-1% vs ~2.65% + 10¢. No monthly fees vs $10+. Crypto + cards.',
    headline: 'PortalPay vs Elavon: Save More, Settle Faster',
    subheadline: 'Transparent pricing, instant settlement, and crypto support.',
    pricing: {
      processingFee: 0.0265,
      flatFee: 0.10,
      monthlyFee: 10,
      annualSoftwareCost: 120,
    },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2.65% + 10¢', advantage: true },
      { feature: 'Monthly Fee', portalpay: '$0', competitor: '$10+', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-2 days', advantage: true },
      { feature: 'Chargebacks', portalpay: 'Zero', competitor: 'Yes', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
    ],
    useCases: [
      { scenario: 'Boutique ($8k/mo)', competitorCost: 2556, portalpayCost: 720, savings: 1836 },
      { scenario: 'Restaurant ($12k/mo)', competitorCost: 3834, portalpayCost: 1080, savings: 2754 },
      { scenario: 'Salon ($6k/mo)', competitorCost: 1917, portalpayCost: 540, savings: 1377 },
    ],
  },

  braintree: {
    slug: 'braintree',
    name: 'Braintree',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs Braintree | Lower Fees + Instant Settlement',
    metaDescription: 'Compare PortalPay vs Braintree. Pay 0.5-1% vs 2.9% + 30¢. No monthly fees. Crypto + cards.',
    headline: 'PortalPay vs Braintree: Modern Payments With Lower Costs',
    subheadline: 'Lower fees, instant settlement, and crypto support without PayPal account holds.',
    pricing: {
      processingFee: 0.029,
      flatFee: 0.30,
      monthlyFee: 0,
      annualSoftwareCost: 0,
    },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2.9% + 30¢', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-3 days', advantage: true },
      { feature: 'Account Holds', portalpay: 'Never', competitor: 'Possible', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: 'Limited', advantage: true },
      { feature: 'Developer API', portalpay: true, competitor: true, advantage: false },
    ],
    useCases: [
      { scenario: 'SaaS ($20k/mo)', competitorCost: 7080, portalpayCost: 1500, savings: 5580 },
      { scenario: 'Marketplace ($25k/mo)', competitorCost: 8850, portalpayCost: 1875, savings: 6975 },
      { scenario: 'Ecommerce ($10k/mo)', competitorCost: 3540, portalpayCost: 750, savings: 2790 },
    ],
  },

  'authorize-net': {
    slug: 'authorize-net',
    name: 'Authorize.Net',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs Authorize.Net | No Monthly Fees + Instant Settlement',
    metaDescription: 'Compare PortalPay vs Authorize.Net. Pay 0.5-1% vs 2.9% + 30¢ + $25/mo. Crypto + cards.',
    headline: 'PortalPay vs Authorize.Net: Lower Fees Without Gateways',
    subheadline: 'Eliminate monthly gateway fees and settle instantly.',
    pricing: {
      processingFee: 0.029,
      flatFee: 0.30,
      monthlyFee: 25,
      annualSoftwareCost: 300,
    },
    features: [
      { feature: 'Monthly Gateway Fee', portalpay: '$0', competitor: '$25+', advantage: true },
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2.9% + 30¢', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-2 days', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
      { feature: 'Developer API', portalpay: true, competitor: true, advantage: false },
    ],
    useCases: [
      { scenario: 'Nonprofit ($12k/mo)', competitorCost: 4830, portalpayCost: 1080, savings: 3750 },
      { scenario: 'Ecom ($15k/mo)', competitorCost: 6075, portalpayCost: 1350, savings: 4725 },
      { scenario: 'Services ($8k/mo)', competitorCost: 3330, portalpayCost: 720, savings: 2610 },
    ],
  },

  'shopify-payments': {
    slug: 'shopify-payments',
    name: 'Shopify Payments',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs Shopify Payments | Lower Fees + No Platform Lock‑In',
    metaDescription: 'Compare PortalPay vs Shopify Payments. Pay 0.5-1% vs 2.9% + 30¢ and platform fees. Crypto + cards.',
    headline: 'PortalPay vs Shopify Payments: Save on Fees and Keep Flexibility',
    subheadline: 'Avoid platform lock‑in and extra fees, with instant settlement.',
    pricing: {
      processingFee: 0.029,
      flatFee: 0.30,
      monthlyFee: 39,
      annualSoftwareCost: 468,
    },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2.9% + 30¢', advantage: true },
      { feature: 'Platform Monthly Fee', portalpay: '$0', competitor: '$39+', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-3 days', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: 'Limited', advantage: true },
      { feature: 'POS/PMS', portalpay: 'Free included', competitor: 'Add‑ons', advantage: true },
    ],
    useCases: [
      { scenario: 'DTC Brand ($20k/mo)', competitorCost: 8348, portalpayCost: 1800, savings: 6548 },
      { scenario: 'Ecommerce ($12k/mo)', competitorCost: 5153, portalpayCost: 1080, savings: 4073 },
      { scenario: 'Subscription ($15k/mo)', competitorCost: 6491, portalpayCost: 1350, savings: 5141 },
    ],
  },

  wepay: {
    slug: 'wepay',
    name: 'WePay (Chase)',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs WePay | Lower Fees + Instant Settlement',
    metaDescription: 'Compare PortalPay vs WePay. Pay 0.5-1% vs 2.9% + 30¢. No account holds. Crypto + cards.',
    headline: 'PortalPay vs WePay: Modern Payments Without Delays',
    subheadline: 'Lower fees and instant settlement without bank hurdles.',
    pricing: {
      processingFee: 0.029,
      flatFee: 0.30,
      monthlyFee: 0,
      annualSoftwareCost: 0,
    },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2.9% + 30¢', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-3 days', advantage: true },
      { feature: 'Account Holds', portalpay: 'Never', competitor: 'Possible', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
    ],
    useCases: [
      { scenario: 'Events ($7k/mo)', competitorCost: 2436, portalpayCost: 630, savings: 1806 },
      { scenario: 'SaaS ($10k/mo)', competitorCost: 3540, portalpayCost: 900, savings: 2640 },
      { scenario: 'Retail ($8k/mo)', competitorCost: 2832, portalpayCost: 720, savings: 2112 },
    ],
  },

  stax: {
    slug: 'stax',
    name: 'Stax',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs Stax | No $99+ Monthly Platform Fee',
    metaDescription: 'Compare PortalPay vs Stax. Pay 0.5-1% vs interchange + $99-$199/mo. Instant settlement. Crypto + cards.',
    headline: 'PortalPay vs Stax: Lower Total Cost Without Subscription',
    subheadline: 'Eliminate large monthly platform fees and get instant settlement.',
    pricing: {
      processingFee: 0.015,
      flatFee: 0.10,
      monthlyFee: 99,
      annualSoftwareCost: 1188,
    },
    features: [
      { feature: 'Monthly Platform Fee', portalpay: '$0', competitor: '$99-$199', advantage: true },
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: 'Interchange + per‑txn', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-2 days', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
    ],
    useCases: [
      { scenario: 'Retail ($12k/mo)', competitorCost: 1188 + 2160, portalpayCost: 1080, savings: 2268 },
      { scenario: 'Restaurant ($15k/mo)', competitorCost: 1188 + 2700, portalpayCost: 1350, savings: 1538 },
      { scenario: 'Pro Services ($8k/mo)', competitorCost: 1188 + 1440, portalpayCost: 720, savings: 1908 },
    ],
  },

  helcim: {
    slug: 'helcim',
    name: 'Helcim',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs Helcim | Lower Fees + Crypto Support',
    metaDescription: 'Compare PortalPay vs Helcim. Pay 0.5-1% vs 2.49% + 25¢. Instant settlement. Crypto + cards.',
    headline: 'PortalPay vs Helcim: Pay Less, Get More',
    subheadline: 'Lower processing fees with instant settlement and crypto support.',
    pricing: {
      processingFee: 0.0249,
      flatFee: 0.25,
      monthlyFee: 0,
      annualSoftwareCost: 0,
    },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2.49% + 25¢', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-2 days', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
      { feature: 'POS', portalpay: 'Free included', competitor: 'Included', advantage: false },
    ],
    useCases: [
      { scenario: 'Retail ($10k/mo)', competitorCost: 3110, portalpayCost: 900, savings: 2210 },
      { scenario: 'Restaurant ($12k/mo)', competitorCost: 3732, portalpayCost: 1080, savings: 2652 },
      { scenario: 'Services ($8k/mo)', competitorCost: 2488, portalpayCost: 720, savings: 1768 },
    ],
  },

  lightspeed: {
    slug: 'lightspeed',
    name: 'Lightspeed POS',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs Lightspeed | Free POS vs $89+/mo',
    metaDescription: 'Compare PortalPay vs Lightspeed. Pay 0.5-1% vs 2.6% + 10¢. Free POS vs $89+/mo. Instant settlement.',
    headline: 'PortalPay vs Lightspeed: Restaurant & Retail Without the POS Tax',
    subheadline: 'Free POS/KDS on any device, instant settlement, and crypto support.',
    pricing: {
      processingFee: 0.026,
      flatFee: 0.10,
      monthlyFee: 89,
      annualSoftwareCost: 1068,
    },
    features: [
      { feature: 'Monthly POS Fee', portalpay: '$0', competitor: '$89+', advantage: true },
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2.6% + 10¢', advantage: true },
      { feature: 'Hardware', portalpay: 'Any device', competitor: 'Preferred hardware', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-2 days', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
    ],
    useCases: [
      { scenario: 'Restaurant ($15k/mo)', competitorCost: 1068 + 4272, portalpayCost: 1350, savings: 3990 },
      { scenario: 'Retail ($12k/mo)', competitorCost: 1068 + 3420, portalpayCost: 1080, savings: 3428 },
      { scenario: 'Cafe ($8k/mo)', competitorCost: 1068 + 2280, portalpayCost: 720, savings: 2628 },
    ],
  },

  touchbistro: {
    slug: 'touchbistro',
    name: 'TouchBistro',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs TouchBistro | Lower Fees + Free POS/KDS',
    metaDescription: 'Compare PortalPay vs TouchBistro. Pay 0.5-1% vs 2.6% + 10¢. Free POS/KDS vs $69+/mo. Instant settlement.',
    headline: 'PortalPay vs TouchBistro: Restaurant‑First Without Monthly Add‑Ons',
    subheadline: 'Free menu, KDS, table management, loyalty, and instant settlement.',
    pricing: {
      processingFee: 0.026,
      flatFee: 0.10,
      monthlyFee: 69,
      annualSoftwareCost: 828,
    },
    features: [
      { feature: 'Monthly POS Fee', portalpay: '$0', competitor: '$69+', advantage: true },
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2.6% + 10¢', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-2 days', advantage: true },
      { feature: 'KDS', portalpay: 'Free included', competitor: 'Add‑on', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
    ],
    useCases: [
      { scenario: 'Casual Dining ($15k/mo)', competitorCost: 828 + 4272, portalpayCost: 1350, savings: 3750 },
      { scenario: 'Cafe ($9k/mo)', competitorCost: 828 + 2565, portalpayCost: 810, savings: 2583 },
      { scenario: 'Fast Casual ($12k/mo)', competitorCost: 828 + 3420, portalpayCost: 1080, savings: 3168 },
    ],
  },

  opennode: {
    slug: 'opennode',
    name: 'OpenNode',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs OpenNode | Cards + Crypto + Lower Effective Cost',
    metaDescription: 'Compare PortalPay vs OpenNode. Pay 0.5-1% vs 1%. Accept cards via onramp. Free POS/PMS. Instant settlement.',
    headline: 'PortalPay vs OpenNode: Business‑Ready Crypto Payments',
    subheadline: 'Get crypto plus cards, POS/PMS, and instant settlement—all at lower effective cost.',
    pricing: {
      processingFee: 0.01,
      flatFee: 0,
      monthlyFee: 0,
      annualSoftwareCost: 0,
    },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '1%', advantage: true },
      { feature: 'Accept Cards', portalpay: 'Yes (onramp)', competitor: 'No', advantage: true },
      { feature: 'POS/PMS', portalpay: 'Free included', competitor: 'Not included', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: 'Instant', advantage: false },
      { feature: 'White‑Label', portalpay: 'Full branding', competitor: 'Limited', advantage: true },
    ],
    migrationSteps: [
      'Keep OpenNode if desired',
      'Add PortalPay for card onramp and POS/PMS',
      'Compare effective costs and features',
    ],
    useCases: [
      { scenario: 'Crypto‑Native Store ($10k/mo)', competitorCost: 1200, portalpayCost: 750, savings: 450 },
      { scenario: 'Events ($7k/mo)', competitorCost: 840, portalpayCost: 525, savings: 315 },
      { scenario: 'Digital Goods ($5k/mo)', competitorCost: 600, portalpayCost: 375, savings: 225 },
    ],
  },
  dutchie: {
    slug: 'dutchie',
    name: 'Dutchie',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs Dutchie | Lower Fees + Crypto Support',
    metaDescription: 'Compare PortalPay vs Dutchie. Pay 0.5-1% vs ≈3.5% + fixed. Instant settlement. Crypto + cards via onramp. Free POS/KDS.',
    headline: 'PortalPay vs Dutchie: Cannabis-Friendly Payments Without High Fees',
    subheadline: 'Lower fees, instant settlement, and crypto support with free POS/KDS and audit-ready reports.',
    pricing: {
      processingFee: 0.035,
      flatFee: 0.15,
      monthlyFee: 0,
      annualSoftwareCost: 0,
    },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '≈3.5% + fixed', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: 'Next-day', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
      { feature: 'Accept Cards', portalpay: 'Yes (onramp)', competitor: 'Limited/No', advantage: true },
      { feature: 'POS/PMS', portalpay: 'Free included', competitor: 'Add-ons', advantage: true },
      { feature: 'Cannabis Compliance', portalpay: 'Audit-ready exports', competitor: 'Basic/partner-dependent', advantage: true },
      { feature: 'Bank Requirement', portalpay: 'No', competitor: 'Yes', advantage: true },
    ],
    migrationSteps: [
      'Export products/menu from Dutchie',
      'Create PortalPay account and connect wallet',
      'Import catalog and configure POS/KDS',
      'Run pilot alongside Dutchie (optional)',
      'Switch fully when ready',
    ],
    useCases: [
      { scenario: 'Dispensary ($25k/mo)', competitorCost: 10500, portalpayCost: 1875, savings: 8625 },
      { scenario: 'Delivery ($15k/mo)', competitorCost: 6300, portalpayCost: 1125, savings: 5175 },
      { scenario: 'CBD Shop ($10k/mo)', competitorCost: 4200, portalpayCost: 750, savings: 3450 },
    ],
  },

  aeropay: {
    slug: 'aeropay',
    name: 'Aeropay',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs Aeropay | Crypto + Cards vs ACH Only',
    metaDescription: 'Compare PortalPay vs Aeropay. Pay 0.5-1% vs ≈1.5% ACH. Instant settlement vs T+1. Crypto + cards via onramp.',
    headline: 'PortalPay vs Aeropay: Broader Payment Options With Lower Total Cost',
    subheadline: 'Go beyond ACH-only. Accept crypto and cards, settle instantly, and get free POS/PMS.',
    pricing: {
      processingFee: 0.015,
      flatFee: 0,
      monthlyFee: 0,
      annualSoftwareCost: 0,
    },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '≈1.5% (ACH)', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: 'T+1', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
      { feature: 'Accept Cards', portalpay: 'Yes (onramp)', competitor: 'No', advantage: true },
      { feature: 'POS/PMS', portalpay: 'Free included', competitor: 'Payment only', advantage: true },
      { feature: 'Bank Requirement', portalpay: 'No', competitor: 'Yes', advantage: true },
    ],
    useCases: [
      { scenario: 'Dispensary ($20k/mo)', competitorCost: 3600, portalpayCost: 1500, savings: 2100 },
      { scenario: 'Delivery ($12k/mo)', competitorCost: 2160, portalpayCost: 900, savings: 1260 },
      { scenario: 'CBD ($8k/mo)', competitorCost: 1440, portalpayCost: 600, savings: 840 },
    ],
  },

  hypur: {
    slug: 'hypur',
    name: 'Hypur',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs Hypur | Lower Fees + Instant Settlement',
    metaDescription: 'Compare PortalPay vs Hypur. Pay 0.5-1% vs ≈2.9% + fixed. Instant settlement vs bank transfer delays. Crypto + cards.',
    headline: 'PortalPay vs Hypur: Modern Cannabis Payments Without Bank Delays',
    subheadline: 'Cut fees and settle instantly with crypto. Accept cards via onramp. Free POS/PMS.',
    pricing: {
      processingFee: 0.029,
      flatFee: 0.20,
      monthlyFee: 0,
      annualSoftwareCost: 0,
    },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '≈2.9% + fixed', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: 'T+1/T+2', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
      { feature: 'Accept Cards', portalpay: 'Yes (onramp)', competitor: 'Limited/No', advantage: true },
      { feature: 'POS/PMS', portalpay: 'Free included', competitor: 'Payment only', advantage: true },
    ],
    useCases: [
      { scenario: 'Dispensary ($18k/mo)', competitorCost: 6264, portalpayCost: 1350, savings: 4914 },
      { scenario: 'CBD ($10k/mo)', competitorCost: 3420, portalpayCost: 750, savings: 2670 },
      { scenario: 'Delivery ($12k/mo)', competitorCost: 4104, portalpayCost: 900, savings: 3204 },
    ],
  },

  paymentcloud: {
    slug: 'paymentcloud',
    name: 'PaymentCloud',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs PaymentCloud | No Monthly Fees + Instant Settlement',
    metaDescription: 'Compare PortalPay vs PaymentCloud. Pay 0.5-1% vs ≈3.5% + 30¢ + monthly fee. Crypto + cards. No contracts.',
    headline: 'PortalPay vs PaymentCloud: High-Risk Friendly Without High Costs',
    subheadline: 'Eliminate monthly fees and contracts. Lower processing cost with instant settlement.',
    pricing: {
      processingFee: 0.035,
      flatFee: 0.30,
      monthlyFee: 25,
      annualSoftwareCost: 300,
    },
    features: [
      { feature: 'Monthly Fee', portalpay: '$0', competitor: '$25+', advantage: true },
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '≈3.5% + 30¢', advantage: true },
      { feature: 'Contracts', portalpay: 'None', competitor: 'Common', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-3 days', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: 'Limited', advantage: true },
    ],
    useCases: [
      { scenario: 'High-Risk Ecom ($15k/mo)', competitorCost: 6570, portalpayCost: 1350, savings: 5220 },
      { scenario: 'Subscription ($10k/mo)', competitorCost: 4380, portalpayCost: 900, savings: 3480 },
      { scenario: 'Marketplace ($12k/mo)', competitorCost: 5256, portalpayCost: 1080, savings: 4176 },
    ],
  },

  paykings: {
    slug: 'paykings',
    name: 'PayKings',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs PayKings | Transparent Pricing + Crypto Support',
    metaDescription: 'Compare PortalPay vs PayKings. Pay 0.5-1% vs high-risk markup. Instant settlement. Crypto + cards.',
    headline: 'PortalPay vs PayKings: Lower Fees, Faster Settlement',
    subheadline: 'Transparent pricing without high-risk markups. Free POS/PMS with crypto support.',
    pricing: {
      processingFee: 0.032,
      flatFee: 0.25,
      monthlyFee: 20,
      annualSoftwareCost: 240,
    },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '≈3.2% + 25¢', advantage: true },
      { feature: 'Monthly Fee', portalpay: '$0', competitor: '$20+', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-3 days', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: 'Limited/No', advantage: true },
      { feature: 'Contracts', portalpay: 'None', competitor: 'Common', advantage: true },
    ],
    useCases: [
      { scenario: 'CBD ($12k/mo)', competitorCost: 5136, portalpayCost: 1080, savings: 4056 },
      { scenario: 'Supplements ($10k/mo)', competitorCost: 4380, portalpayCost: 900, savings: 3480 },
      { scenario: 'Adult Content ($8k/mo)', competitorCost: 3504, portalpayCost: 600, savings: 2904 },
    ],
  },

  'durango-merchant-services': {
    slug: 'durango-merchant-services',
    name: 'Durango Merchant Services',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs Durango Merchant Services | Lower Fees + No Contracts',
    metaDescription: 'Compare PortalPay vs Durango Merchant Services. Pay 0.5-1% vs ≈3% + fixed. No monthly fees. Instant settlement. Crypto + cards.',
    headline: 'PortalPay vs Durango: High-Risk Friendly Without Overpaying',
    subheadline: 'Transparent pricing, instant settlement, and broader payment options.',
    pricing: {
      processingFee: 0.03,
      flatFee: 0.20,
      monthlyFee: 0,
      annualSoftwareCost: 0,
    },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '≈3% + fixed', advantage: true },
      { feature: 'Contracts', portalpay: 'None', competitor: 'Common', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-2 days', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: 'Limited/No', advantage: true },
      { feature: 'POS/PMS', portalpay: 'Free included', competitor: 'Payment only', advantage: true },
    ],
    useCases: [
      { scenario: 'High-Risk Ecom ($15k/mo)', competitorCost: 5400, portalpayCost: 1350, savings: 4050 },
      { scenario: 'CBD ($10k/mo)', competitorCost: 3600, portalpayCost: 900, savings: 2700 },
      { scenario: 'Adult ($8k/mo)', competitorCost: 2880, portalpayCost: 600, savings: 2280 },
    ],
  },
  // Cannabis PIN debit network vs crypto+cards
  canpay: {
    slug: 'canpay',
    name: 'CanPay',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs CanPay | Crypto + Cards vs PIN Debit Only',
    metaDescription: 'Compare PortalPay vs CanPay. Accept crypto + cards vs PIN debit network only. Lower fees, instant settlement, free POS/KDS.',
    headline: 'PortalPay vs CanPay: Broader Payment Options With Lower Costs',
    subheadline: 'Serve all customers with crypto and cards, not just those with CanPay. Settle instantly.',
    pricing: {
      processingFee: 0.015,
      flatFee: 0,
      monthlyFee: 0,
      annualSoftwareCost: 0,
    },
    features: [
      { feature: 'Payment Options', portalpay: 'Crypto + Cards', competitor: 'PIN Debit Network', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: 'T+1', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
      { feature: 'POS/PMS', portalpay: 'Free included', competitor: 'Payment only', advantage: true },
    ],
    useCases: [
      { scenario: 'Dispensary ($20k/mo)', competitorCost: 3000, portalpayCost: 1500, savings: 1500 },
      { scenario: 'Delivery ($12k/mo)', competitorCost: 1800, portalpayCost: 900, savings: 900 },
      { scenario: 'CBD ($8k/mo)', competitorCost: 1200, portalpayCost: 600, savings: 600 },
    ],
  },

  // Cannabis POS platforms
  'cova-pos': {
    slug: 'cova-pos',
    name: 'Cova POS',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs Cova POS | Free POS/KDS + Lower Fees',
    metaDescription: 'Compare PortalPay vs Cova POS. Pay 0.5-1% vs 2.6% + 10¢. Free POS/KDS, instant settlement, crypto + cards.',
    headline: 'PortalPay vs Cova: Restaurant/Retail‑grade POS Without Monthly Add‑Ons',
    subheadline: 'Free POS/KDS on any device with instant settlement and crypto support.',
    pricing: {
      processingFee: 0.026,
      flatFee: 0.10,
      monthlyFee: 69,
      annualSoftwareCost: 828,
    },
    features: [
      { feature: 'Monthly POS Fee', portalpay: '$0', competitor: '$69+', advantage: true },
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2.6% + 10¢', advantage: true },
      { feature: 'KDS', portalpay: 'Free included', competitor: 'Add‑on', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
    ],
    useCases: [
      { scenario: 'Dispensary ($15k/mo)', competitorCost: 828 + 4272, portalpayCost: 1350, savings: 3750 },
      { scenario: 'Retail ($12k/mo)', competitorCost: 828 + 3420, portalpayCost: 1080, savings: 3168 },
      { scenario: 'CBD ($9k/mo)', competitorCost: 828 + 2565, portalpayCost: 810, savings: 2583 },
    ],
  },

  flowhub: {
    slug: 'flowhub',
    name: 'Flowhub',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs Flowhub | Lower Fees + Crypto Support',
    metaDescription: 'Compare PortalPay vs Flowhub. Pay 0.5-1% vs ~2.9% + fixed. Free POS/KDS, instant settlement, crypto + cards.',
    headline: 'PortalPay vs Flowhub: Cannabis‑Friendly Payments Without High Fees',
    subheadline: 'Lower fees with instant settlement and broader payment options.',
    pricing: {
      processingFee: 0.029,
      flatFee: 0.20,
      monthlyFee: 69,
      annualSoftwareCost: 828,
    },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '≈2.9% + fixed', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: 'T+1/T+2', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
      { feature: 'POS/KDS', portalpay: 'Free included', competitor: 'Monthly add‑ons', advantage: true },
    ],
    useCases: [
      { scenario: 'Dispensary ($18k/mo)', competitorCost: 828 + 6264, portalpayCost: 1350, savings: 5742 },
      { scenario: 'CBD ($10k/mo)', competitorCost: 828 + 3420, portalpayCost: 750, savings: 3498 },
      { scenario: 'Delivery ($12k/mo)', competitorCost: 828 + 4104, portalpayCost: 900, savings: 4032 },
    ],
  },

  treez: {
    slug: 'treez',
    name: 'Treez',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs Treez | Free POS + Lower Payment Fees',
    metaDescription: 'Compare PortalPay vs Treez. Pay 0.5-1% vs 2.6% + 10¢. Free POS/KDS, instant settlement, crypto + cards.',
    headline: 'PortalPay vs Treez: Cut Fees and Keep Flexibility',
    subheadline: 'Lower payment fees, instant settlement, and no hardware lock‑in.',
    pricing: {
      processingFee: 0.026,
      flatFee: 0.10,
      monthlyFee: 89,
      annualSoftwareCost: 1068,
    },
    features: [
      { feature: 'Monthly POS Fee', portalpay: '$0', competitor: '$89+', advantage: true },
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2.6% + 10¢', advantage: true },
      { feature: 'Hardware', portalpay: 'Any device', competitor: 'Preferred hardware', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
    ],
    useCases: [
      { scenario: 'Dispensary ($20k/mo)', competitorCost: 1068 + 6840, portalpayCost: 1500, savings: 6408 },
      { scenario: 'Retail ($12k/mo)', competitorCost: 1068 + 3420, portalpayCost: 1080, savings: 3408 },
      { scenario: 'CBD ($9k/mo)', competitorCost: 1068 + 2565, portalpayCost: 810, savings: 2823 },
    ],
  },

  // Global and gateway providers
  rapyd: {
    slug: 'rapyd',
    name: 'Rapyd',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs Rapyd | Lower Fees + Crypto Support',
    metaDescription: 'Compare PortalPay vs Rapyd. Pay 0.5-1% vs ~2.9% + fixed. Instant settlement. Crypto + cards.',
    headline: 'PortalPay vs Rapyd: Modern Payments Without FX Markups',
    subheadline: 'Lower fees, instant settlement, and crypto support with free POS/PMS.',
    pricing: { processingFee: 0.029, flatFee: 0.20, monthlyFee: 0, annualSoftwareCost: 0 },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2.9% + 20¢', advantage: true },
      { feature: 'International Fees', portalpay: 'None', competitor: '1-3% FX', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: 'Limited', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-2 days', advantage: true },
    ],
    useCases: [
      { scenario: 'Global Ecom ($25k/mo)', competitorCost: 8850, portalpayCost: 1875, savings: 6975 },
      { scenario: 'Marketplace ($15k/mo)', competitorCost: 5310, portalpayCost: 1125, savings: 4185 },
      { scenario: 'SaaS ($10k/mo)', competitorCost: 3540, portalpayCost: 750, savings: 2790 },
    ],
  },

  bluesnap: {
    slug: 'bluesnap',
    name: 'BlueSnap',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs BlueSnap | Lower Fees + Instant Settlement',
    metaDescription: 'Compare PortalPay vs BlueSnap. Pay 0.5-1% vs ~2.9% + 30¢. Crypto + cards. No monthly fees.',
    headline: 'PortalPay vs BlueSnap: Save on Fees and Settle Faster',
    subheadline: 'Lower cost and instant settlement with free POS/PMS.',
    pricing: { processingFee: 0.029, flatFee: 0.30, monthlyFee: 0, annualSoftwareCost: 0 },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2.9% + 30¢', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-3 days', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: 'Limited', advantage: true },
      { feature: 'Monthly Fee', portalpay: '$0', competitor: '$0-50+', advantage: true },
    ],
    useCases: [
      { scenario: 'Ecom ($12k/mo)', competitorCost: 4464, portalpayCost: 1080, savings: 3384 },
      { scenario: 'SaaS ($15k/mo)', competitorCost: 5310, portalpayCost: 1350, savings: 3960 },
      { scenario: 'Services ($8k/mo)', competitorCost: 2832, portalpayCost: 720, savings: 2112 },
    ],
  },

  nmi: {
    slug: 'nmi',
    name: 'NMI (Gateway)',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs NMI | No Gateway Fees + Crypto Support',
    metaDescription: 'Compare PortalPay vs NMI. Pay 0.5-1% vs gateway fees + processor fees. Instant settlement, crypto + cards.',
    headline: 'PortalPay vs NMI: Eliminate Gateway Fees',
    subheadline: 'Lower total cost by removing monthly gateway charges.',
    pricing: { processingFee: 0.0275, flatFee: 0.20, monthlyFee: 15, annualSoftwareCost: 180 },
    features: [
      { feature: 'Monthly Gateway Fee', portalpay: '$0', competitor: '$15+', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-2 days', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
      { feature: 'POS/PMS', portalpay: 'Free included', competitor: 'Gateway only', advantage: true },
    ],
    useCases: [
      { scenario: 'Retail ($10k/mo)', competitorCost: 180 + 3420, portalpayCost: 900, savings: 2700 },
      { scenario: 'Restaurant ($12k/mo)', competitorCost: 180 + 4104, portalpayCost: 1080, savings: 3204 },
      { scenario: 'SaaS ($15k/mo)', competitorCost: 180 + 5310, portalpayCost: 1350, savings: 4140 },
    ],
  },

  nuvei: {
    slug: 'nuvei',
    name: 'Nuvei',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs Nuvei | Lower Fees + Instant Settlement',
    metaDescription: 'Compare PortalPay vs Nuvei. Pay 0.5-1% vs ~2.75% + fixed. Crypto + cards. No contracts.',
    headline: 'PortalPay vs Nuvei: Transparent, Fast, and Affordable',
    subheadline: 'Stop overpaying with contracts. Get instant settlement and crypto support.',
    pricing: { processingFee: 0.0275, flatFee: 0.20, monthlyFee: 0, annualSoftwareCost: 0 },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2.75% + 20¢', advantage: true },
      { feature: 'Contracts', portalpay: 'None', competitor: 'Common', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-3 days', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: 'Limited', advantage: true },
    ],
    useCases: [
      { scenario: 'Retail ($10k/mo)', competitorCost: 3420, portalpayCost: 900, savings: 2520 },
      { scenario: 'Restaurant ($12k/mo)', competitorCost: 4104, portalpayCost: 1080, savings: 3024 },
      { scenario: 'Services ($8k/mo)', competitorCost: 2736, portalpayCost: 720, savings: 2016 },
    ],
  },

  paysafe: {
    slug: 'paysafe',
    name: 'Paysafe',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs Paysafe | Lower Fees + Crypto Support',
    metaDescription: 'Compare PortalPay vs Paysafe. Pay 0.5-1% vs ~2.9% + fixed. Instant settlement. Crypto + cards.',
    headline: 'PortalPay vs Paysafe: Modern Payments Without Overhead',
    subheadline: 'Lower fees, instant settlement, and crypto support with free POS/PMS.',
    pricing: { processingFee: 0.029, flatFee: 0.20, monthlyFee: 0, annualSoftwareCost: 0 },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2.9% + 20¢', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-2 days', advantage: true },
      { feature: 'International Fees', portalpay: 'None', competitor: '1-3% FX', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: 'Limited', advantage: true },
    ],
    useCases: [
      { scenario: 'Ecom ($12k/mo)', competitorCost: 4464, portalpayCost: 1080, savings: 3384 },
      { scenario: 'Marketplace ($20k/mo)', competitorCost: 7080, portalpayCost: 1800, savings: 5280 },
      { scenario: 'SaaS ($10k/mo)', competitorCost: 3540, portalpayCost: 750, savings: 2790 },
    ],
  },

  cybersource: {
    slug: 'cybersource',
    name: 'CyberSource (Visa)',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs CyberSource | No Gateway Fees + Instant Settlement',
    metaDescription: 'Compare PortalPay vs CyberSource. Pay 0.5-1% vs 2.9% + 30¢ + gateway fees. Crypto + cards.',
    headline: 'PortalPay vs CyberSource: Lower Total Cost Without Gateways',
    subheadline: 'Eliminate monthly gateway fees and settle instantly.',
    pricing: { processingFee: 0.029, flatFee: 0.30, monthlyFee: 25, annualSoftwareCost: 300 },
    features: [
      { feature: 'Monthly Gateway Fee', portalpay: '$0', competitor: '$25+', advantage: true },
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2.9% + 30¢', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-2 days', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: 'Limited', advantage: true },
    ],
    useCases: [
      { scenario: 'Subscription ($15k/mo)', competitorCost: 6075 + 300, portalpayCost: 1350, savings: 5025 },
      { scenario: 'Retail ($12k/mo)', competitorCost: 4464 + 300, portalpayCost: 1080, savings: 3684 },
      { scenario: 'Services ($8k/mo)', competitorCost: 2832 + 300, portalpayCost: 720, savings: 2412 },
    ],
  },

  '2checkout': {
    slug: '2checkout',
    name: '2Checkout (Verifone)',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs 2Checkout | Lower Fees + Instant Settlement',
    metaDescription: 'Compare PortalPay vs 2Checkout. Pay 0.5-1% vs ~3.5% + fixed. Crypto + cards.',
    headline: 'PortalPay vs 2Checkout: Save on Fees and Settle Faster',
    subheadline: 'Lower cost and instant settlement with free POS/PMS.',
    pricing: { processingFee: 0.035, flatFee: 0.30, monthlyFee: 0, annualSoftwareCost: 0 },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '≈3.5% + fixed', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-3 days', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: 'No', advantage: true },
      { feature: 'International Fees', portalpay: 'None', competitor: '1-3% FX', advantage: true },
    ],
    useCases: [
      { scenario: 'Ecom ($20k/mo)', competitorCost: 8400, portalpayCost: 1800, savings: 6600 },
      { scenario: 'SaaS ($15k/mo)', competitorCost: 6300, portalpayCost: 1350, savings: 4950 },
      { scenario: 'Services ($10k/mo)', competitorCost: 4200, portalpayCost: 750, savings: 3450 },
    ],
  },

  moneris: {
    slug: 'moneris',
    name: 'Moneris',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs Moneris | Lower Fees + Crypto Support',
    metaDescription: 'Compare PortalPay vs Moneris. Pay 0.5-1% vs ~2.75% + fixed. Instant settlement. Crypto + cards.',
    headline: 'PortalPay vs Moneris: Transparent, Fast, and Affordable',
    subheadline: 'Lower fees and instant settlement with free POS/PMS.',
    pricing: { processingFee: 0.0275, flatFee: 0.20, monthlyFee: 15, annualSoftwareCost: 180 },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2.75% + 20¢', advantage: true },
      { feature: 'Monthly Fee', portalpay: '$0', competitor: '$15+', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-3 days', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: 'No', advantage: true },
    ],
    useCases: [
      { scenario: 'Retail ($10k/mo)', competitorCost: 3420 + 180, portalpayCost: 900, savings: 2700 },
      { scenario: 'Restaurant ($12k/mo)', competitorCost: 4104 + 180, portalpayCost: 1080, savings: 3204 },
      { scenario: 'Services ($8k/mo)', competitorCost: 2736 + 180, portalpayCost: 720, savings: 2196 },
    ],
  },

  'evo-payments': {
    slug: 'evo-payments',
    name: 'EVO Payments',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs EVO Payments | Lower Fees + Instant Settlement',
    metaDescription: 'Compare PortalPay vs EVO Payments. Pay 0.5-1% vs ~2.75% + fixed. Crypto + cards.',
    headline: 'PortalPay vs EVO: Save on Fees and Settle Faster',
    subheadline: 'Transparent pricing, instant settlement, and crypto support.',
    pricing: { processingFee: 0.0275, flatFee: 0.20, monthlyFee: 0, annualSoftwareCost: 0 },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2.75% + 20¢', advantage: true },
      { feature: 'Contracts', portalpay: 'None', competitor: 'Common', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-3 days', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: 'Limited', advantage: true },
    ],
    useCases: [
      { scenario: 'Retail ($10k/mo)', competitorCost: 3420, portalpayCost: 900, savings: 2520 },
      { scenario: 'Restaurant ($12k/mo)', competitorCost: 4104, portalpayCost: 1080, savings: 3024 },
      { scenario: 'Services ($8k/mo)', competitorCost: 2736, portalpayCost: 720, savings: 2016 },
    ],
  },

  woocommerce: {
    slug: 'woocommerce',
    name: 'WooCommerce',
    logo: '/logos/woocommerce.svg',
    title: 'PortalPay vs WooCommerce | Headless Payments vs Plugin Stack',
    metaDescription: 'Compare PortalPay vs WooCommerce. API-first headless payments vs WordPress plugin-based ecommerce. Lower fees, instant settlement, B2B workflows.',
    headline: 'PortalPay vs WooCommerce: Headless API-First vs Plugin Stack',
    subheadline: 'Choose modern API-first payments with crypto support, or traditional WordPress ecommerce with a large plugin marketplace.',
    pricing: { processingFee: 0.029, flatFee: 0.30, monthlyFee: 0, annualSoftwareCost: 0 },
    features: [
      { feature: 'Architecture', portalpay: 'API-first, headless by design', competitor: 'WordPress plugin-based', advantage: true },
      { feature: 'Developer Experience', portalpay: 'REST + GraphQL APIs, typed objects', competitor: 'PHP/WordPress plugin ecosystem', advantage: true },
      { feature: 'B2B Workflows', portalpay: 'Receipts, reserve, users, split, tax APIs', competitor: 'Requires multiple add-ons or plugins', advantage: true },
      { feature: 'Headless / Omnichannel', portalpay: 'First-class (POS, kiosks, custom apps)', competitor: 'Primarily web storefront, headless via plugins', advantage: true },
      { feature: 'Processing Fees', portalpay: '0.5-1%', competitor: 'Depends on gateway (typically 2.9% + 30¢)', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-3 days (gateway dependent)', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: 'Via add-ons', advantage: true },
      { feature: 'Surcharging / Routing', portalpay: 'Programmable policies via APIs', competitor: 'Typically custom or plugin-dependent', advantage: true },
      { feature: 'Compliance & Tax', portalpay: 'Tax API + audit-friendly primitives', competitor: '3rd-party tax plugins recommended', advantage: true },
      { feature: 'Security Model', portalpay: 'Keyed access via API Management', competitor: 'WordPress auth + plugin permissions', advantage: true },
      { feature: 'Scalability', portalpay: 'Cloud-native, edge-friendly API surface', competitor: 'Varies by host, caching, and plugins', advantage: true },
      { feature: 'Extensibility', portalpay: 'Compose domain APIs for bespoke flows', competitor: 'Large plugin marketplace', advantage: false },
      { feature: 'Bank Requirement', portalpay: 'No', competitor: 'Yes (for most gateways)', advantage: true },
    ],
    migrationSteps: [
      'Export products and customer data from WooCommerce',
      'Set up PortalPay account with crypto wallet',
      'Use REST/GraphQL APIs to integrate with your stack',
      'Build custom storefront or use existing headless solution',
      'Migrate product catalog via API',
      'Configure payment flows and B2B workflows as needed',
      'Test transactions end-to-end',
      'Switch DNS/traffic when ready',
    ],
    useCases: [
      { scenario: 'Ecommerce Store ($15k/mo)', competitorCost: 5310, portalpayCost: 1125, savings: 4185 },
      { scenario: 'Subscription Business ($20k/mo)', competitorCost: 7080, portalpayCost: 1500, savings: 5580 },
      { scenario: 'Marketplace ($25k/mo)', competitorCost: 8850, portalpayCost: 1875, savings: 6975 },
      { scenario: 'B2B Platform ($30k/mo)', competitorCost: 10620, portalpayCost: 2250, savings: 8370 },
    ],
  },

  // ============================================
  // SUBSCRIPTION & BILLING PLATFORMS
  // ============================================
  recurly: {
    slug: 'recurly',
    name: 'Recurly',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs Recurly | Lower Fees + Crypto Subscriptions',
    metaDescription: 'Compare PortalPay vs Recurly. Pay 0.5-1% vs 2.9% + 25¢ + platform fees. Instant settlement. Crypto-native recurring billing.',
    headline: 'PortalPay vs Recurly: Subscription Billing Without Platform Tax',
    subheadline: 'Lower fees, instant settlement, and crypto-native recurring payments without monthly platform charges.',
    pricing: { processingFee: 0.029, flatFee: 0.25, monthlyFee: 199, annualSoftwareCost: 2388 },
    features: [
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2.9% + 25¢', advantage: true },
      { feature: 'Monthly Platform Fee', portalpay: '$0', competitor: '$199+', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-3 days', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
      { feature: 'Dunning Management', portalpay: 'Built-in', competitor: 'Built-in', advantage: false },
      { feature: 'Revenue Recognition', portalpay: 'API-based', competitor: 'Advanced tools', advantage: false },
    ],
    useCases: [
      { scenario: 'SaaS Startup ($15k/mo)', competitorCost: 2388 + 5310, portalpayCost: 1350, savings: 6348 },
      { scenario: 'Media Subscription ($25k/mo)', competitorCost: 2388 + 8850, portalpayCost: 2250, savings: 8988 },
      { scenario: 'Enterprise SaaS ($50k/mo)', competitorCost: 2388 + 17700, portalpayCost: 4500, savings: 15588 },
    ],
  },

  chargebee: {
    slug: 'chargebee',
    name: 'Chargebee',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs Chargebee | Lower Fees + No Revenue Share',
    metaDescription: 'Compare PortalPay vs Chargebee. Pay 0.5-1% vs platform fees + payment processing. Instant settlement. Crypto subscriptions.',
    headline: 'PortalPay vs Chargebee: Subscription Management Without Revenue Tax',
    subheadline: 'Eliminate revenue-based platform fees and settle instantly with crypto support.',
    pricing: { processingFee: 0.029, flatFee: 0.30, monthlyFee: 299, annualSoftwareCost: 3588 },
    features: [
      { feature: 'Platform Fee', portalpay: '$0', competitor: '$299-599/mo + revenue %', advantage: true },
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2.9% + 30¢ (via gateway)', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-3 days', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
      { feature: 'Revenue Analytics', portalpay: 'Dashboard included', competitor: 'Advanced analytics', advantage: false },
    ],
    useCases: [
      { scenario: 'SaaS ($20k/mo)', competitorCost: 3588 + 7080, portalpayCost: 1800, savings: 8868 },
      { scenario: 'Subscription Box ($12k/mo)', competitorCost: 3588 + 4464, portalpayCost: 1080, savings: 6972 },
      { scenario: 'Digital Membership ($30k/mo)', competitorCost: 3588 + 10620, portalpayCost: 2700, savings: 11508 },
    ],
  },

  zuora: {
    slug: 'zuora',
    name: 'Zuora',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs Zuora | Enterprise Billing Without Enterprise Pricing',
    metaDescription: 'Compare PortalPay vs Zuora. Lower fees without complex enterprise contracts. Instant settlement. Crypto support.',
    headline: 'PortalPay vs Zuora: Enterprise Subscription Features at SMB Pricing',
    subheadline: 'Get subscription billing features without six-figure annual contracts.',
    pricing: { processingFee: 0.029, flatFee: 0.30, monthlyFee: 1000, annualSoftwareCost: 12000 },
    features: [
      { feature: 'Annual Contract', portalpay: 'None', competitor: '$50,000+ typical', advantage: true },
      { feature: 'Implementation', portalpay: 'Self-serve', competitor: 'Months + consulting', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-3 days', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
      { feature: 'Revenue Recognition', portalpay: 'API-based', competitor: 'ASC 606 compliant', advantage: false },
    ],
    useCases: [
      { scenario: 'Growth SaaS ($50k/mo)', competitorCost: 12000 + 17700, portalpayCost: 4500, savings: 25200 },
      { scenario: 'Enterprise ($100k/mo)', competitorCost: 12000 + 35400, portalpayCost: 9000, savings: 38400 },
    ],
  },

  chargify: {
    slug: 'chargify',
    name: 'Chargify (Maxio)',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs Chargify | Lower Fees + Instant Settlement',
    metaDescription: 'Compare PortalPay vs Chargify/Maxio. Pay 0.5-1% vs platform fees. Crypto subscriptions available.',
    headline: 'PortalPay vs Chargify: B2B Billing Without Platform Overhead',
    subheadline: 'Eliminate monthly platform charges with instant settlement and crypto support.',
    pricing: { processingFee: 0.029, flatFee: 0.25, monthlyFee: 599, annualSoftwareCost: 7188 },
    features: [
      { feature: 'Monthly Fee', portalpay: '$0', competitor: '$599+', advantage: true },
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2.9% + 25¢', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-3 days', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
    ],
    useCases: [
      { scenario: 'B2B SaaS ($25k/mo)', competitorCost: 7188 + 8850, portalpayCost: 2250, savings: 13788 },
      { scenario: 'Usage-Based ($18k/mo)', competitorCost: 7188 + 6372, portalpayCost: 1620, savings: 11940 },
    ],
  },

  // ============================================
  // CREATOR & DIGITAL GOODS PLATFORMS
  // ============================================
  gumroad: {
    slug: 'gumroad',
    name: 'Gumroad',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs Gumroad | 90% Less in Fees for Creators',
    metaDescription: 'Compare PortalPay vs Gumroad. Pay 0.5-1% vs 10% flat fee. Keep more of your sales. Instant settlement.',
    headline: 'PortalPay vs Gumroad: Keep 99% Instead of 90%',
    subheadline: 'Stop giving away 10% of every sale. Lower fees, instant settlement, and crypto support.',
    pricing: { processingFee: 0.10, flatFee: 0, monthlyFee: 0, annualSoftwareCost: 0 },
    features: [
      { feature: 'Platform Fee', portalpay: '0.5-1%', competitor: '10% flat', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: 'Weekly', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
      { feature: 'Digital Delivery', portalpay: 'Via integrations', competitor: 'Built-in', advantage: false },
      { feature: 'Audience Building', portalpay: 'Via integrations', competitor: 'Email tools', advantage: false },
    ],
    useCases: [
      { scenario: 'Digital Creator ($5k/mo)', competitorCost: 6000, portalpayCost: 450, savings: 5550 },
      { scenario: 'Course Seller ($15k/mo)', competitorCost: 18000, portalpayCost: 1350, savings: 16650 },
      { scenario: 'Digital Products ($10k/mo)', competitorCost: 12000, portalpayCost: 900, savings: 11100 },
    ],
  },

  sellix: {
    slug: 'sellix',
    name: 'Sellix',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs Sellix | Lower Fees for Digital Goods',
    metaDescription: 'Compare PortalPay vs Sellix. Pay 0.5-1% vs 5-15% fees. Crypto-native. Instant settlement.',
    headline: 'PortalPay vs Sellix: Digital Commerce Without High Takes',
    subheadline: 'Lower platform fees and keep more of your digital product sales.',
    pricing: { processingFee: 0.05, flatFee: 0, monthlyFee: 0, annualSoftwareCost: 0 },
    features: [
      { feature: 'Platform Fee', portalpay: '0.5-1%', competitor: '5-15%', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: 'Varies', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: true, advantage: false },
      { feature: 'Digital Delivery', portalpay: 'Via integrations', competitor: 'Built-in', advantage: false },
    ],
    useCases: [
      { scenario: 'Digital Goods ($8k/mo)', competitorCost: 4800, portalpayCost: 720, savings: 4080 },
      { scenario: 'Software Keys ($12k/mo)', competitorCost: 7200, portalpayCost: 1080, savings: 6120 },
    ],
  },

  'lemon-squeezy': {
    slug: 'lemon-squeezy',
    name: 'Lemon Squeezy',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs Lemon Squeezy | Lower Fees for Software Creators',
    metaDescription: 'Compare PortalPay vs Lemon Squeezy. Pay 0.5-1% vs 5% + payment fees. Instant settlement.',
    headline: 'PortalPay vs Lemon Squeezy: Keep More of Your Software Sales',
    subheadline: 'Avoid the 5% platform tax while getting instant settlement and crypto support.',
    pricing: { processingFee: 0.05, flatFee: 0.50, monthlyFee: 0, annualSoftwareCost: 0 },
    features: [
      { feature: 'Platform Fee', portalpay: '0.5-1%', competitor: '5% + processing', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '2-7 days', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
      { feature: 'Tax Handling', portalpay: 'Via integrations', competitor: 'MoR included', advantage: false },
      { feature: 'License Keys', portalpay: 'Via integrations', competitor: 'Built-in', advantage: false },
    ],
    useCases: [
      { scenario: 'Indie Dev ($6k/mo)', competitorCost: 3600 + 2088, portalpayCost: 540, savings: 5148 },
      { scenario: 'SaaS Template ($10k/mo)', competitorCost: 6000 + 3480, portalpayCost: 900, savings: 8580 },
    ],
  },

  payhip: {
    slug: 'payhip',
    name: 'Payhip',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs Payhip | Lower Transaction Fees',
    metaDescription: 'Compare PortalPay vs Payhip. Pay 0.5-1% vs 5% + payment fees. Better for digital creators.',
    headline: 'PortalPay vs Payhip: Sell Digital Products With Lower Fees',
    subheadline: 'Keep more revenue with lower transaction fees and instant settlement.',
    pricing: { processingFee: 0.05, flatFee: 0, monthlyFee: 0, annualSoftwareCost: 0 },
    features: [
      { feature: 'Transaction Fee', portalpay: '0.5-1%', competitor: '5% + processing', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: 'PayPal/Stripe timing', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
    ],
    useCases: [
      { scenario: 'Ebook Seller ($3k/mo)', competitorCost: 1800 + 1044, portalpayCost: 270, savings: 2574 },
      { scenario: 'Digital Art ($7k/mo)', competitorCost: 4200 + 2436, portalpayCost: 630, savings: 6006 },
    ],
  },

  sendowl: {
    slug: 'sendowl',
    name: 'SendOwl',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs SendOwl | No Monthly Fees + Lower Processing',
    metaDescription: 'Compare PortalPay vs SendOwl. Pay 0.5-1% vs $9-39/mo + processing. Better for digital sellers.',
    headline: 'PortalPay vs SendOwl: Digital Delivery Without Monthly Subscriptions',
    subheadline: 'Eliminate monthly platform fees while getting instant settlement.',
    pricing: { processingFee: 0.029, flatFee: 0.30, monthlyFee: 15, annualSoftwareCost: 180 },
    features: [
      { feature: 'Monthly Fee', portalpay: '$0', competitor: '$9-39/mo', advantage: true },
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2.9% + 30¢ (via gateway)', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: 'Gateway dependent', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
    ],
    useCases: [
      { scenario: 'Small Creator ($2k/mo)', competitorCost: 180 + 696, portalpayCost: 180, savings: 696 },
      { scenario: 'Growing Creator ($8k/mo)', competitorCost: 468 + 2784, portalpayCost: 720, savings: 2532 },
    ],
  },

  paykickstart: {
    slug: 'paykickstart',
    name: 'PayKickstart',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs PayKickstart | Lower Total Cost for Funnels',
    metaDescription: 'Compare PortalPay vs PayKickstart. Pay 0.5-1% vs $99-299/mo + processing. Instant settlement.',
    headline: 'PortalPay vs PayKickstart: Checkout Without High Monthly Fees',
    subheadline: 'Build sales funnels without $99-299/month platform costs.',
    pricing: { processingFee: 0.029, flatFee: 0.30, monthlyFee: 149, annualSoftwareCost: 1788 },
    features: [
      { feature: 'Monthly Fee', portalpay: '$0', competitor: '$99-299/mo', advantage: true },
      { feature: 'Processing Fee', portalpay: '0.5-1%', competitor: '2.9% + 30¢', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-3 days', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
      { feature: 'Funnel Builder', portalpay: 'Via integrations', competitor: 'Built-in', advantage: false },
    ],
    useCases: [
      { scenario: 'Info Product ($10k/mo)', competitorCost: 1788 + 3540, portalpayCost: 900, savings: 4428 },
      { scenario: 'Course Creator ($20k/mo)', competitorCost: 1788 + 7080, portalpayCost: 1800, savings: 7068 },
    ],
  },

  samcart: {
    slug: 'samcart',
    name: 'SamCart',
    logo: '/logos/Untitled-2.png',
    title: 'PortalPay vs SamCart | Lower Fees for Digital Products',
    metaDescription: 'Compare PortalPay vs SamCart. Pay 0.5-1% vs $79-319/mo + 1% + processing. Instant settlement.',
    headline: 'PortalPay vs SamCart: Checkout Pages Without Platform Tax',
    subheadline: 'Eliminate monthly fees and 1% transaction charges.',
    pricing: { processingFee: 0.029, flatFee: 0.30, monthlyFee: 199, annualSoftwareCost: 2388 },
    features: [
      { feature: 'Monthly Fee', portalpay: '$0', competitor: '$79-319/mo', advantage: true },
      { feature: 'Transaction Fee', portalpay: '0.5-1%', competitor: '1% + processing', advantage: true },
      { feature: 'Settlement', portalpay: 'Instant', competitor: '1-3 days', advantage: true },
      { feature: 'Accept Crypto', portalpay: true, competitor: false, advantage: true },
    ],
    useCases: [
      { scenario: 'Course Creator ($12k/mo)', competitorCost: 2388 + 1440 + 4176, portalpayCost: 1080, savings: 6924 },
      { scenario: 'Coaching ($18k/mo)', competitorCost: 2388 + 2160 + 6264, portalpayCost: 1620, savings: 9192 },
    ],
  },
};

export function getComparisonData(slug: string): ComparisonData | null {
  return COMPARISON_DATA[slug] || null;
}

export function getAllComparisons(): ComparisonData[] {
  return Object.values(COMPARISON_DATA);
}
