package com.example.basaltsurgemobile.plugins

import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.util.Base64
import android.util.Log
import com.example.basaltsurgemobile.hardware.DeviceProfile
import com.example.basaltsurgemobile.hardware.DeviceType
import com.example.basaltsurgemobile.hardware.HardwareRegistry
import com.getcapacitor.JSObject
import com.getcapacitor.Plugin
import com.getcapacitor.PluginCall
import com.getcapacitor.PluginMethod
import com.getcapacitor.annotation.CapacitorPlugin

@CapacitorPlugin(name = "SecondaryDisplay")
class SecondaryDisplayPlugin : Plugin() {

    companion object {
        const val TAG = "SecondaryDisplayPlugin"
    }

    @PluginMethod
    fun displayQR(call: PluginCall) {
        if (DeviceProfile.type != DeviceType.TOPWISE_T6D) {
            call.reject("Secondary display not supported on this device.")
            return
        }

        val qrData = call.getString("data")
        val base64Img = call.getString("base64")

        val screen = HardwareRegistry.topWiseManager?.smallScreen
        if (screen == null) {
            call.reject("TopWise Small Screen not available")
            return
        }

        try {
            // T6D Small Screen is 282x240 dots
            // Display base64 image if provided, otherwise standard text
            if (base64Img != null) {
                val decodedString = Base64.decode(base64Img.substringAfter(","), Base64.DEFAULT)
                var bmp = BitmapFactory.decodeByteArray(decodedString, 0, decodedString.size)
                
                // Scale down to fit the customer screen
                bmp = Bitmap.createScaledBitmap(bmp, 200, 200, false)
                screen.showImage(bmp)
            } else if (qrData != null) {
                // If the AIDL does not natively render QRs, we usually just clear the screen 
                // and pass actual bitmaps generated by JS. For now, clearing.
                screen.cleanScreen()
                // Assuming JS will send the canvas as base64 in production.
            }
            
            val res = JSObject()
            res.put("success", true)
            call.resolve(res)
        } catch (e: Exception) {
            Log.e(TAG, "Failed setting secondary display", e)
            call.reject("Exception setting secondary display: ${e.message}")
        }
    }

    @PluginMethod
    fun clearDisplay(call: PluginCall) {
        if (DeviceProfile.type == DeviceType.TOPWISE_T6D) {
            try {
                HardwareRegistry.topWiseManager?.smallScreen?.cleanScreen()
                call.resolve()
            } catch (e: Exception) {
                call.reject("Failed clearing secondary display", e)
            }
        } else {
            call.resolve()
        }
    }
}
