package com.example.basaltsurgemobile.plugins

import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.util.Base64
import android.util.Log
import com.example.basaltsurgemobile.hardware.DeviceProfile
import com.example.basaltsurgemobile.hardware.DeviceType
import com.example.basaltsurgemobile.hardware.HardwareRegistry
import com.getcapacitor.JSObject
import com.getcapacitor.Plugin
import com.getcapacitor.PluginCall
import com.getcapacitor.PluginMethod
import com.getcapacitor.annotation.CapacitorPlugin

@CapacitorPlugin(name = "TopWiseDisplay")
class TopWiseDisplayPlugin : Plugin() {

    companion object {
        const val TAG = "TopWiseDisplayPlugin"
    }

    @PluginMethod
    fun displayQR(call: PluginCall) {

        val qrData = call.getString("data")
        val base64Img = call.getString("base64")

        val screen = HardwareRegistry.topWiseManager?.smallScreenManager
        if (screen == null) {
            call.reject("TopWise Small Screen not available")
            return
        }

        try {
            // Wake up screen and take control from the OS clock
            screen.wakeSmallScreen()
            
            // T6D Small Screen is 282x240 dots
            // Display base64 image if provided, otherwise standard text
            if (base64Img != null) {
                val decodedString = Base64.decode(base64Img.substringAfter(","), Base64.DEFAULT)
                var bmp = BitmapFactory.decodeByteArray(decodedString, 0, decodedString.size)
                
                // Scale down to fit the customer screen
                bmp = Bitmap.createScaledBitmap(bmp, 200, 200, false)
                screen.displayBitmap(bmp, com.topwise.cloudpos.aidl.smallscreen.BitmapAlign.BITMAP_ALIGN_CENTER)
            } else if (qrData != null) {
                // If the AIDL does not natively render QRs, we usually just clear the screen 
                // and pass actual bitmaps generated by JS. For now, clearing.
                screen.displayText("", com.topwise.cloudpos.aidl.smallscreen.SmallScreenTextSize.TEXT_SIZE_NORMAL, com.topwise.cloudpos.aidl.smallscreen.SmallScreenDisplayMode.TEXT_DISPLAY_MODE_UP_NORMAL)
                // Assuming JS will send the canvas as base64 in production.
            }
            
            val res = JSObject()
            res.put("success", true)
            call.resolve(res)
        } catch (e: Exception) {
            Log.e(TAG, "Failed setting secondary display", e)
            call.reject("Exception setting secondary display: ${e.message}")
        }
    }

    @PluginMethod
    fun clearDisplay(call: PluginCall) {
        try {
            // Return control to the OS to show the default clock
            HardwareRegistry.topWiseManager?.smallScreenManager?.stopAppControl()
            call.resolve()
        } catch (e: Exception) {
            call.reject("Failed clearing secondary display", e)
        }
    }
}
